# Makefile generated by the project manager
#


# GENERATED: Sun Oct 30 10:48:18 +0800 2016
# DO NOT EDIT - file is regenerated whenever the project changes


## core information

ifeq ($(wildcard Makefile.mk),)
PRJ_DIR        = ..
else
PRJ_DIR        = .
endif
PRJ_FILE       = VehicleImage.wpj
PRJ_FULL_PATH  = $(WIND_HOME)/MyWorkspace/VehicleImage
PRJ_TYPE       = vxWorks
PRJ_OBJS       = sysALib.o sysLib.o usrAppInit.o usrRtpAppInit.o prjConfig.o linkSyms.o TestPciCan.o dtp.o TestIoCnt.o RtcLib.o AppEntry.o CanModule.o ComModule.o IoCntModule.o MangeFile.o MangeUsb.o usb2Msc.o usb2MscXBD.o
PRJ_MAKEFILE   = $(PRJ_DIR)/Makefile.mk
BOOT_OBJS      = romInit.o romStart.o $(BOOT_EXTRA)
BUILD_SPEC     = default
BSP_DIR        = $(TGT_DIR)/config/CD6011_bsp
VSB_DIR        = $(TGT_DIR)/lib
TGT_DIR        = $(WIND_BASE)/target



## set searching directories for dependencies

vpath %.c $(BSP_DIR)
vpath %.cpp $(BSP_DIR)
vpath %.cxx $(BSP_DIR)
vpath %.s $(BSP_DIR)


## build-configuration info

ifeq ($(BUILD_SPEC),default)
CPU            = PENTIUM4
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks
endif

ifeq ($(BUILD_SPEC),default_rom)
CPU            = PENTIUM4
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks_rom
endif

ifeq ($(BUILD_SPEC),default_romCompress)
CPU            = PENTIUM4
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks_romCompress
endif

ifeq ($(BUILD_SPEC),default_romResident)
CPU            = PENTIUM4
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks_romResident
endif


## Memory adresses variables

RAM_LOW_ADRS = 00408000
RAM_HIGH_ADRS = 00108000
LOCAL_MEM_LOCAL_ADRS = (0x00100000)

## component-configuration info

COMPONENTS = DRV_KBD_I8042 \
	DRV_NVRAM_FILE \
	DRV_SIO_NS16550 \
	DRV_TIMER_I8253 \
	DRV_VGA_M6845 \
	INCLUDE_ANSI_ABORT \
	INCLUDE_ANSI_ABS \
	INCLUDE_ANSI_ASSERT \
	INCLUDE_ANSI_ATOF \
	INCLUDE_ANSI_BSEARCH \
	INCLUDE_ANSI_CTYPE \
	INCLUDE_ANSI_LOCALE \
	INCLUDE_ANSI_LONGJMP \
	INCLUDE_ANSI_MATH \
	INCLUDE_ANSI_MEMCHR \
	INCLUDE_ANSI_MEMCMP \
	INCLUDE_ANSI_MEMCPY \
	INCLUDE_ANSI_MEMMOVE \
	INCLUDE_ANSI_MEMSET \
	INCLUDE_ANSI_STDIO \
	INCLUDE_ANSI_STDIO_EXTRA \
	INCLUDE_ANSI_STDLIB \
	INCLUDE_ANSI_STDLIB_NUMBERS \
	INCLUDE_ANSI_STRCASECMP \
	INCLUDE_ANSI_STRCAT \
	INCLUDE_ANSI_STRCMP \
	INCLUDE_ANSI_STRCPY \
	INCLUDE_ANSI_STRDUP \
	INCLUDE_ANSI_STRERROR \
	INCLUDE_ANSI_STRING \
	INCLUDE_ANSI_STRLCPY \
	INCLUDE_ANSI_STRLEN \
	INCLUDE_ANSI_STRNCASECMP \
	INCLUDE_ANSI_STRNCAT \
	INCLUDE_ANSI_STRNCMP \
	INCLUDE_ANSI_STRNCPY \
	INCLUDE_ANSI_STRTOD \
	INCLUDE_ANSI_TIME \
	INCLUDE_APPL_LOG_UTIL \
	INCLUDE_ATOMIC_OPERATORS \
	INCLUDE_AVL_UINT_TREES \
	INCLUDE_BASE_KERNEL \
	INCLUDE_BLIB \
	INCLUDE_BOOT_LINE_INIT \
	INCLUDE_BSP_MACROS \
	INCLUDE_CACHE_ENABLE \
	INCLUDE_CACHE_SUPPORT \
	INCLUDE_CLASS_LIB \
	INCLUDE_CLASS_LIST \
	INCLUDE_COMMON_NET \
	INCLUDE_COPROCESSOR \
	INCLUDE_COPROCESSOR_SHOW \
	INCLUDE_CPU_LIGHT_PWR_MGR \
	INCLUDE_CPU_PWR_MGMT \
	INCLUDE_CTORS_DTORS \
	INCLUDE_DEBUG \
	INCLUDE_DEVICE_MANAGER \
	INCLUDE_DISK_UTIL \
	INCLUDE_DLL \
	INCLUDE_DMA_SYS \
	INCLUDE_DOSFS \
	INCLUDE_DOSFS_CHKDSK \
	INCLUDE_DOSFS_DIR_FIXED \
	INCLUDE_DOSFS_DIR_VFAT \
	INCLUDE_DOSFS_FAT \
	INCLUDE_DOSFS_FMT \
	INCLUDE_DOSFS_MAIN \
	INCLUDE_DOSFS_SHOW \
	INCLUDE_DOSFS_VOL_BIO_BUFFER_SIZE \
	INCLUDE_DRV_STORAGE_INTEL_ICH \
	INCLUDE_DRV_STORAGE_INTEL_ICH_SHOW \
	INCLUDE_EDR_STUB \
	INCLUDE_EDR_SYSDBG_FLAG \
	INCLUDE_EHCI \
	INCLUDE_EHCI_BUS \
	INCLUDE_EHCI_INIT \
	INCLUDE_END \
	INCLUDE_END_COMMON \
	INCLUDE_END_ETHER_HDR \
	INCLUDE_ENV_VARS \
	INCLUDE_ERF \
	INCLUDE_EVENTPOINT_STUB \
	INCLUDE_EXC_HANDLING \
	INCLUDE_EXC_SHOW \
	INCLUDE_EXC_TASK \
	INCLUDE_FLOATING_POINT \
	INCLUDE_FORMATTED_IO \
	INCLUDE_FORMATTED_OUT_BASIC \
	INCLUDE_FP_TYPE \
	INCLUDE_FS_EVENT_UTIL \
	INCLUDE_FS_MONITOR \
	INCLUDE_FTP \
	INCLUDE_GEI825XX_VXB_END \
	INCLUDE_GENERICPHY \
	INCLUDE_GETOPT \
	INCLUDE_GNU_INTRINSICS \
	INCLUDE_HANDLE_SHOW \
	INCLUDE_HASH \
	INCLUDE_HOOKS \
	INCLUDE_HOST_TBL \
	INCLUDE_HWMEM_ALLOC \
	INCLUDE_HW_FP \
	INCLUDE_IFCONFIG \
	INCLUDE_IO_BASIC \
	INCLUDE_IO_FILE_SYSTEM \
	INCLUDE_IO_MISC \
	INCLUDE_IO_POSIX \
	INCLUDE_IO_REMOVABLE \
	INCLUDE_IO_RTP \
	INCLUDE_IO_SYSTEM \
	INCLUDE_IPAIP \
	INCLUDE_IPAIP_GLOBAL_CONFIGS \
	INCLUDE_IPCOM \
	INCLUDE_IPCOM_SHELL_CMD \
	INCLUDE_IPCOM_USE_AUTH \
	INCLUDE_IPCOM_USE_ETHERNET \
	INCLUDE_IPCOM_USE_INET \
	INCLUDE_IPFTPS \
	INCLUDE_IPIFCONFIG_CMD \
	INCLUDE_IPNET \
	INCLUDE_IPNET_IFCONFIG_1 \
	INCLUDE_IPNET_LOOPBACK_CONFIG \
	INCLUDE_IPNET_SOCKET \
	INCLUDE_IPNET_STACK \
	INCLUDE_IPNET_USE_LOOPBACK \
	INCLUDE_IPNET_USE_ROUTESOCK \
	INCLUDE_IPNET_USE_SOCK_COMPAT \
	INCLUDE_IPPROXYARP \
	INCLUDE_IPTCP \
	INCLUDE_IPV4 \
	INCLUDE_IPWRAP_IFCONFIG \
	INCLUDE_IPWRAP_INETLIB \
	INCLUDE_ISR_DEFER \
	INCLUDE_JOB_QUEUE \
	INCLUDE_JOB_TASK \
	INCLUDE_KERNEL \
	INCLUDE_KERNEL_ARCH \
	INCLUDE_LINKBUFPOOL \
	INCLUDE_LOADER \
	INCLUDE_LOADER_CODE \
	INCLUDE_LOGGING \
	INCLUDE_LSTLIB \
	INCLUDE_MBUF_UTIL1 \
	INCLUDE_MEMORY_CONFIG \
	INCLUDE_MEM_MGR_BASIC \
	INCLUDE_MEM_MGR_FULL \
	INCLUDE_MEM_MGR_INFO \
	INCLUDE_MII_BUS \
	INCLUDE_MMU_BASIC \
	INCLUDE_MMU_GLOBAL_MAP \
	INCLUDE_MMU_P6_32BIT \
	INCLUDE_MODULE_MANAGER \
	INCLUDE_MSG_Q \
	INCLUDE_MSG_Q_CREATE_DELETE \
	INCLUDE_MSG_Q_EVENTS \
	INCLUDE_MSG_Q_INFO \
	INCLUDE_MUX \
	INCLUDE_MUX2 \
	INCLUDE_MUX2_OVER_END \
	INCLUDE_MUXTK \
	INCLUDE_MUXTK_OVER_END \
	INCLUDE_MUX_COMMON \
	INCLUDE_NBIO_LOG \
	INCLUDE_NETBUFLIB \
	INCLUDE_NETBUFPOOL \
	INCLUDE_NETMASK_GET \
	INCLUDE_NETWORK \
	INCLUDE_NET_BOOT \
	INCLUDE_NET_DAEMON \
	INCLUDE_NET_DRV \
	INCLUDE_NET_HOST_SETUP \
	INCLUDE_NET_REM_IO \
	INCLUDE_NON_VOLATILE_RAM \
	INCLUDE_OBJ_INFO \
	INCLUDE_OBJ_LIB \
	INCLUDE_OFFSET_SYMBOLS \
	INCLUDE_OHCI \
	INCLUDE_OHCI_BUS \
	INCLUDE_OHCI_INIT \
	INCLUDE_PARAM_SYS \
	INCLUDE_PCI_BUS \
	INCLUDE_PCI_OLD_CONFIG_ROUTINES \
	INCLUDE_PC_CONSOLE \
	INCLUDE_PENTIUM_PCI \
	INCLUDE_PIPES \
	INCLUDE_PLB_BUS \
	INCLUDE_POOL \
	INCLUDE_POSIX_CLOCKS \
	INCLUDE_POSIX_DIRLIB \
	INCLUDE_POSIX_FS \
	INCLUDE_PTYDRV \
	INCLUDE_Q_FIFO \
	INCLUDE_Q_LIB \
	INCLUDE_Q_PRI_BMAP \
	INCLUDE_Q_PRI_DELTA \
	INCLUDE_Q_PRI_LIST \
	INCLUDE_RAWFS \
	INCLUDE_REBOOT_HOOKS \
	INCLUDE_REMLIB \
	INCLUDE_RNG_BUF \
	INCLUDE_SECURITY \
	INCLUDE_SELECT \
	INCLUDE_SELECT_SUPPORT \
	INCLUDE_SEM_BINARY \
	INCLUDE_SEM_BINARY_CREATE \
	INCLUDE_SEM_COUNTING \
	INCLUDE_SEM_COUNTING_CREATE \
	INCLUDE_SEM_DELETE \
	INCLUDE_SEM_EVENTS \
	INCLUDE_SEM_INFO \
	INCLUDE_SEM_LIB \
	INCLUDE_SEM_MUTEX \
	INCLUDE_SEM_MUTEX_CREATE \
	INCLUDE_SEM_READ_WRITE \
	INCLUDE_SEM_READ_WRITE_CREATE \
	INCLUDE_SHELL \
	INCLUDE_SHELL_CORE \
	INCLUDE_SHELL_INTERP_C \
	INCLUDE_SHELL_VI_MODE \
	INCLUDE_SIGNALS \
	INCLUDE_SIGNAL_ARCH \
	INCLUDE_SIO \
	INCLUDE_SIO_UTILS \
	INCLUDE_SLL \
	INCLUDE_SOCKLIB \
	INCLUDE_SPINLOCK \
	INCLUDE_STANDALONE_SYM_TBL \
	INCLUDE_STDIO \
	INCLUDE_SYM_TBL \
	INCLUDE_SYM_TBL_INIT \
	INCLUDE_SYM_TBL_SHOW \
	INCLUDE_SYSCLK_INIT \
	INCLUDE_SYSCTL \
	INCLUDE_SYSHW_INIT \
	INCLUDE_SYSHW_INIT2 \
	INCLUDE_SYS_START \
	INCLUDE_TASK_CREATE_DELETE \
	INCLUDE_TASK_CREATE_HOOKS \
	INCLUDE_TASK_HOOKS \
	INCLUDE_TASK_INFO \
	INCLUDE_TASK_LIST \
	INCLUDE_TASK_RESTART \
	INCLUDE_TASK_SHOW \
	INCLUDE_TASK_SWAP_HOOKS \
	INCLUDE_TASK_SWITCH_HOOKS \
	INCLUDE_TASK_UTIL \
	INCLUDE_TASK_VARS \
	INCLUDE_THERM_MONITOR \
	INCLUDE_TIMER_SYS \
	INCLUDE_TIMER_SYS_DELAY \
	INCLUDE_TIMEX \
	INCLUDE_TIP \
	INCLUDE_TTY_DEV \
	INCLUDE_TYLIB \
	INCLUDE_UHCI \
	INCLUDE_UHCI_BUS \
	INCLUDE_UHCI_INIT \
	INCLUDE_UNLOADER \
	INCLUDE_USB \
	INCLUDE_USB_GEN2_HELPER \
	INCLUDE_USB_GEN2_STORAGE \
	INCLUDE_USB_GEN2_STORAGE_INIT \
	INCLUDE_USB_INIT \
	INCLUDE_USER_APPL \
	INCLUDE_VXBUS \
	INCLUDE_VXBUS_ACTIVATE \
	INCLUDE_VXBUS_DEVICE_CONNECT \
	INCLUDE_VXBUS_DEV_INIT \
	INCLUDE_VXBUS_INIT \
	INCLUDE_VXB_SYS_CLK \
	INCLUDE_VXEVENTS \
	INCLUDE_VXMEMPROBE_INIT \
	INCLUDE_VXMUX_MBLK \
	INCLUDE_VXMUX_NULLBUFPOOL \
	INCLUDE_VX_TRADITIONAL_SCHEDULER \
	INCLUDE_WATCHDOGS \
	INCLUDE_WATCHDOGS_CREATE_DELETE \
	INCLUDE_WB_RUNTIME_SUPPORT \
	INCLUDE_WDB \
	INCLUDE_WDB_BANNER \
	INCLUDE_WDB_BP \
	INCLUDE_WDB_BP_SYNC \
	INCLUDE_WDB_COMM_END \
	INCLUDE_WDB_CTXT \
	INCLUDE_WDB_DIRECT_CALL \
	INCLUDE_WDB_EVENTPOINTS \
	INCLUDE_WDB_EVENTS \
	INCLUDE_WDB_EXC_NOTIFY \
	INCLUDE_WDB_EXIT_NOTIFY \
	INCLUDE_WDB_FUNC_CALL \
	INCLUDE_WDB_GOPHER \
	INCLUDE_WDB_KERNEL_INIT_DONE \
	INCLUDE_WDB_MDL_SYM_SYNC \
	INCLUDE_WDB_MEM \
	INCLUDE_WDB_POST_KERNEL_INIT \
	INCLUDE_WDB_REG \
	INCLUDE_WDB_START_NOTIFY \
	INCLUDE_WDB_SYS \
	INCLUDE_WDB_SYS_REG \
	INCLUDE_WDB_TASK \
	INCLUDE_WDB_TASK_BP \
	INCLUDE_WDB_TASK_HOOKS \
	INCLUDE_WDB_TASK_REG \
	INCLUDE_WDB_USER_EVENT \
	INCLUDE_WDB_VIO \
	INCLUDE_WDB_VIO_LIB \
	INCLUDE_XBD \
	INCLUDE_XBD_BLK_DEV \
	INCLUDE_XBD_PART_LIB \
	INIT_HWMEMPOOL_GLOBAL \
	VXBUS_TABLE_CONFIG

MANAGED_LIBS = libar521x.a libar521xVxbEnd.a libbcm43xx.a libbcm43xxVxbEnd.a libspl.a libtipc.a libvxdot1x.a libwlan.a libwlanVxbEnd.a
COMPONENT_LIBS = libspl.a

PROJECT_LINK_SYMDEFS = 


include $(TGT_DIR)/h/make/defs.project


## build-configuration info

ifeq ($(BUILD_SPEC),default)
AR               = arpentium
AS               = ccpentium
BOOT_EXTRA       = 
CC               = ccpentium
CC_ARCH_SPEC     = -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop
CFLAGS           = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS        = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS_PROJECT = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CFLAGS_PROJECT   = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CPP              = ccpentium -E -P
EXTRA_MODULES    = $(BSP_DIR)/KEY/vxbI8042Kbd.o $(BSP_DIR)/APIC/vxbIoApicIntr.o $(BSP_DIR)/ICH/vxbIntelIchStorage.o $(BSP_DIR)/PIO/PciIoCntLib.o $(BSP_DIR)/ICH/bootFsLoad.o $(BSP_DIR)/PCAN/PciCanLib.o $(BSP_DIR)/SIO/vxbNs16550Sio.o $(SUB_TARGETS)
LD               = ldpentium
LD_LINK_PATH     = -L$(VSB_DIR)/pentium/PENTIUM4/gnu_standard -L$(VSB_DIR)/pentium/PENTIUM4/gnu -L$(VSB_DIR)/pentium/PENTIUM4/common -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/common -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/gnu -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/common
LD_PARTIAL       = ccpentium -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmpentium -g
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
SIZE             = sizepentium
TOOL_FAMILY      = gnu
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_rom)
AR               = arpentium
AS               = ccpentium
BOOT_EXTRA       = 
CC               = ccpentium
CC_ARCH_SPEC     = -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop
CFLAGS           = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS        = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS_PROJECT = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CFLAGS_PROJECT   = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CPP              = ccpentium -E -P
EXTRA_MODULES    = $(BSP_DIR)/KEY/vxbI8042Kbd.o $(BSP_DIR)/APIC/vxbIoApicIntr.o $(BSP_DIR)/ICH/vxbIntelIchStorage.o $(BSP_DIR)/PIO/PciIoCntLib.o $(BSP_DIR)/ICH/bootFsLoad.o $(BSP_DIR)/PCAN/PciCanLib.o $(BSP_DIR)/SIO/vxbNs16550Sio.o $(BSP_DIR)/USB/usb2MscXBD.o $(BSP_DIR)/USB/usb2Msc.o $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = ldpentium
LD_LINK_PATH     = -L$(VSB_DIR)/pentium/PENTIUM4/gnu_standard -L$(VSB_DIR)/pentium/PENTIUM4/gnu -L$(VSB_DIR)/pentium/PENTIUM4/common -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/common -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/gnu -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/common
LD_PARTIAL       = ccpentium -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmpentium -g
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
ROM_SIZE         = 00090000	# number of bytes of ROM space
ROM_TEXT_ADRS    = 00008000	# ROM entry address - A: or C:
SIZE             = sizepentium
TOOL_FAMILY      = gnu
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romCompress)
AR               = arpentium
AS               = ccpentium
BOOT_EXTRA       = 
CC               = ccpentium
CC_ARCH_SPEC     = -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop
CFLAGS           = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS        = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS_PROJECT = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CFLAGS_PROJECT   = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CPP              = ccpentium -E -P
EXTRA_MODULES    = $(BSP_DIR)/KEY/vxbI8042Kbd.o $(BSP_DIR)/APIC/vxbIoApicIntr.o $(BSP_DIR)/ICH/vxbIntelIchStorage.o $(BSP_DIR)/PIO/PciIoCntLib.o $(BSP_DIR)/ICH/bootFsLoad.o $(BSP_DIR)/PCAN/PciCanLib.o $(BSP_DIR)/SIO/vxbNs16550Sio.o $(BSP_DIR)/USB/usb2MscXBD.o $(BSP_DIR)/USB/usb2Msc.o $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = ldpentium
LD_LINK_PATH     = -L$(VSB_DIR)/pentium/PENTIUM4/gnu_standard -L$(VSB_DIR)/pentium/PENTIUM4/gnu -L$(VSB_DIR)/pentium/PENTIUM4/common -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/common -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/gnu -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/common
LD_PARTIAL       = ccpentium -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmpentium -g
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
ROM_SIZE         = 00090000	# number of bytes of ROM space
ROM_TEXT_ADRS    = 00008000	# ROM entry address - A: or C:
SIZE             = sizepentium
TOOL_FAMILY      = gnu
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romResident)
AR               = arpentium
AS               = ccpentium
BOOT_EXTRA       = 
CC               = ccpentium
CC_ARCH_SPEC     = -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop
CFLAGS           = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS        = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS_PROJECT = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CFLAGS_PROJECT   = -g -mtune=pentium4 -march=pentium4 -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM4 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CPP              = ccpentium -E -P
EXTRA_MODULES    = $(BSP_DIR)/KEY/vxbI8042Kbd.o $(BSP_DIR)/APIC/vxbIoApicIntr.o $(BSP_DIR)/ICH/vxbIntelIchStorage.o $(BSP_DIR)/PIO/PciIoCntLib.o $(BSP_DIR)/ICH/bootFsLoad.o $(BSP_DIR)/PCAN/PciCanLib.o $(BSP_DIR)/SIO/vxbNs16550Sio.o $(BSP_DIR)/USB/usb2MscXBD.o $(BSP_DIR)/USB/usb2Msc.o $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = ldpentium
LD_LINK_PATH     = -L$(VSB_DIR)/pentium/PENTIUM4/gnu_standard -L$(VSB_DIR)/pentium/PENTIUM4/gnu -L$(VSB_DIR)/pentium/PENTIUM4/common -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/common -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/gnu -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM4/common
LD_PARTIAL       = ccpentium -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmpentium -g
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
ROM_SIZE         = 00090000	# number of bytes of ROM space
ROM_TEXT_ADRS    = 00008000	# ROM entry address - A: or C:
SIZE             = sizepentium
TOOL_FAMILY      = gnu
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

# override make definitions only below this line


# override make definitions only above this line

include $(TGT_DIR)/h/make/rules.project


## build-configuration info

sysALib.o: $(PRJ_DIR)/prjParams.h

ifeq ($(BUILD_SPEC),default)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

TestPciCan.o:  $(PRJ_DIR)/SRC/Driver/can/TestPciCan.c 
	$(RM) TestPciCan.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/can/TestPciCan.c

dtp.o:  $(PRJ_DIR)/SRC/Driver/dtp/dtp.c 
	$(RM) dtp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/dtp/dtp.c

TestIoCnt.o:  $(PRJ_DIR)/SRC/Driver/iocnt/TestIoCnt.c 
	$(RM) TestIoCnt.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/iocnt/TestIoCnt.c

RtcLib.o:  $(PRJ_DIR)/SRC/Driver/rtc/RtcLib.c 
	$(RM) RtcLib.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/rtc/RtcLib.c

AppEntry.o:  $(PRJ_DIR)/SRC/User/AppEntry/AppEntry.c 
	$(RM) AppEntry.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/AppEntry/AppEntry.c

CanModule.o:  $(PRJ_DIR)/SRC/User/CanModule/CanModule.c 
	$(RM) CanModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/CanModule/CanModule.c

ComModule.o:  $(PRJ_DIR)/SRC/User/ComModule/ComModule.c 
	$(RM) ComModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/ComModule/ComModule.c

IoCntModule.o:  $(PRJ_DIR)/SRC/User/IoCtModule/IoCntModule.c 
	$(RM) IoCntModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/IoCtModule/IoCntModule.c

MangeFile.o:  $(PRJ_DIR)/SRC/User/ManageFile/MangeFile.c 
	$(RM) MangeFile.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/ManageFile/MangeFile.c

MangeUsb.o:  $(PRJ_DIR)/SRC/User/MangeUsb/MangeUsb.c 
	$(RM) MangeUsb.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/MangeUsb/MangeUsb.c

usb2Msc.o:  $(PRJ_DIR)/SRC/Driver/usb/usb2Msc.c 
	$(RM) usb2Msc.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/usb/usb2Msc.c

usb2MscXBD.o:  $(PRJ_DIR)/SRC/Driver/usb/usb2MscXBD.c 
	$(RM) usb2MscXBD.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/usb/usb2MscXBD.c
endif

ifeq ($(BUILD_SPEC),default_rom)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

TestPciCan.o:  $(PRJ_DIR)/SRC/Driver/can/TestPciCan.c 
	$(RM) TestPciCan.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/can/TestPciCan.c

dtp.o:  $(PRJ_DIR)/SRC/Driver/dtp/dtp.c 
	$(RM) dtp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/dtp/dtp.c

TestIoCnt.o:  $(PRJ_DIR)/SRC/Driver/iocnt/TestIoCnt.c 
	$(RM) TestIoCnt.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/iocnt/TestIoCnt.c

RtcLib.o:  $(PRJ_DIR)/SRC/Driver/rtc/RtcLib.c 
	$(RM) RtcLib.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/rtc/RtcLib.c

AppEntry.o:  $(PRJ_DIR)/SRC/User/AppEntry/AppEntry.c 
	$(RM) AppEntry.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/AppEntry/AppEntry.c

CanModule.o:  $(PRJ_DIR)/SRC/User/CanModule/CanModule.c 
	$(RM) CanModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/CanModule/CanModule.c

ComModule.o:  $(PRJ_DIR)/SRC/User/ComModule/ComModule.c 
	$(RM) ComModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/ComModule/ComModule.c

IoCntModule.o:  $(PRJ_DIR)/SRC/User/IoCtModule/IoCntModule.c 
	$(RM) IoCntModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/IoCtModule/IoCntModule.c

MangeFile.o:  $(PRJ_DIR)/SRC/User/ManageFile/MangeFile.c 
	$(RM) MangeFile.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/ManageFile/MangeFile.c

MangeUsb.o:  $(PRJ_DIR)/SRC/User/MangeUsb/MangeUsb.c 
	$(RM) MangeUsb.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/MangeUsb/MangeUsb.c

usb2Msc.o:  $(PRJ_DIR)/SRC/Driver/usb/usb2Msc.c 
	$(RM) usb2Msc.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/usb/usb2Msc.c

usb2MscXBD.o:  $(PRJ_DIR)/SRC/Driver/usb/usb2MscXBD.c 
	$(RM) usb2MscXBD.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/usb/usb2MscXBD.c
endif

ifeq ($(BUILD_SPEC),default_romCompress)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

TestPciCan.o:  $(PRJ_DIR)/SRC/Driver/can/TestPciCan.c 
	$(RM) TestPciCan.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/can/TestPciCan.c

dtp.o:  $(PRJ_DIR)/SRC/Driver/dtp/dtp.c 
	$(RM) dtp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/dtp/dtp.c

TestIoCnt.o:  $(PRJ_DIR)/SRC/Driver/iocnt/TestIoCnt.c 
	$(RM) TestIoCnt.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/iocnt/TestIoCnt.c

RtcLib.o:  $(PRJ_DIR)/SRC/Driver/rtc/RtcLib.c 
	$(RM) RtcLib.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/rtc/RtcLib.c

AppEntry.o:  $(PRJ_DIR)/SRC/User/AppEntry/AppEntry.c 
	$(RM) AppEntry.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/AppEntry/AppEntry.c

CanModule.o:  $(PRJ_DIR)/SRC/User/CanModule/CanModule.c 
	$(RM) CanModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/CanModule/CanModule.c

ComModule.o:  $(PRJ_DIR)/SRC/User/ComModule/ComModule.c 
	$(RM) ComModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/ComModule/ComModule.c

IoCntModule.o:  $(PRJ_DIR)/SRC/User/IoCtModule/IoCntModule.c 
	$(RM) IoCntModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/IoCtModule/IoCntModule.c

MangeFile.o:  $(PRJ_DIR)/SRC/User/ManageFile/MangeFile.c 
	$(RM) MangeFile.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/ManageFile/MangeFile.c

MangeUsb.o:  $(PRJ_DIR)/SRC/User/MangeUsb/MangeUsb.c 
	$(RM) MangeUsb.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/MangeUsb/MangeUsb.c

usb2Msc.o:  $(PRJ_DIR)/SRC/Driver/usb/usb2Msc.c 
	$(RM) usb2Msc.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/usb/usb2Msc.c

usb2MscXBD.o:  $(PRJ_DIR)/SRC/Driver/usb/usb2MscXBD.c 
	$(RM) usb2MscXBD.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/usb/usb2MscXBD.c
endif

ifeq ($(BUILD_SPEC),default_romResident)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

TestPciCan.o:  $(PRJ_DIR)/SRC/Driver/can/TestPciCan.c 
	$(RM) TestPciCan.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/can/TestPciCan.c

dtp.o:  $(PRJ_DIR)/SRC/Driver/dtp/dtp.c 
	$(RM) dtp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/dtp/dtp.c

TestIoCnt.o:  $(PRJ_DIR)/SRC/Driver/iocnt/TestIoCnt.c 
	$(RM) TestIoCnt.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/iocnt/TestIoCnt.c

RtcLib.o:  $(PRJ_DIR)/SRC/Driver/rtc/RtcLib.c 
	$(RM) RtcLib.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/rtc/RtcLib.c

AppEntry.o:  $(PRJ_DIR)/SRC/User/AppEntry/AppEntry.c 
	$(RM) AppEntry.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/AppEntry/AppEntry.c

CanModule.o:  $(PRJ_DIR)/SRC/User/CanModule/CanModule.c 
	$(RM) CanModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/CanModule/CanModule.c

ComModule.o:  $(PRJ_DIR)/SRC/User/ComModule/ComModule.c 
	$(RM) ComModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/ComModule/ComModule.c

IoCntModule.o:  $(PRJ_DIR)/SRC/User/IoCtModule/IoCntModule.c 
	$(RM) IoCntModule.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/IoCtModule/IoCntModule.c

MangeFile.o:  $(PRJ_DIR)/SRC/User/ManageFile/MangeFile.c 
	$(RM) MangeFile.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/ManageFile/MangeFile.c

MangeUsb.o:  $(PRJ_DIR)/SRC/User/MangeUsb/MangeUsb.c 
	$(RM) MangeUsb.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/User/MangeUsb/MangeUsb.c

usb2Msc.o:  $(PRJ_DIR)/SRC/Driver/usb/usb2Msc.c 
	$(RM) usb2Msc.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/usb/usb2Msc.c

usb2MscXBD.o:  $(PRJ_DIR)/SRC/Driver/usb/usb2MscXBD.c 
	$(RM) usb2MscXBD.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SRC/Driver/usb/usb2MscXBD.c
endif


## user defined rules

romStart.o : $(TGT_DIR)/config/comps/src/romStart.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(ROM_FLAGS_EXTRA) $< -o $@

romcard_bootrom_512.hex: depend.$(BSP_NAME) romcard.o bootrom_uncmp
	- @ $(RM) $@
	$(LD) -o romcard -X -N -e _romcard romcard.o
	$(ROMSIZEPROG) -b 7fe00 bootrom_uncmp
	$(BINHEX) -a 0 bootrom_uncmp | $(SED) -e "/S9/d" > $@
	$(BINHEX) -a 7fe00 -b romcard >> $@
	- @ $(RM) romcard.o romcard
	$(POST_HEX_BUILD_RULE)

#   bootrom		- bootrom(compressed):		   upper mem

romInit.o : $(TGT_DIR)/config/CD6011_bsp/romInit.s
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS_AS) $(CFLAGS_AS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(ROM_FLAGS_EXTRA) $< -o $@

linkSyms.o : $(PRJ_DIR)/linkSyms.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/linkSyms.c -o $@

#   bootrom_uncmp	- bootrom:			   upper mem

romcard_bootrom_256.hex: depend.$(BSP_NAME) romcard.o bootrom_uncmp
	- @ $(RM) $@
	$(LD) -o romcard -X -N -e _romcard romcard.o
	$(ROMSIZEPROG) -b 3fe00 bootrom_uncmp
	$(BINHEX) -a 0 bootrom_uncmp | $(SED) -e "/S9/d" > $@
	$(BINHEX) -a 3fe00 -b romcard >> $@
	- @ $(RM) romcard.o romcard
	$(POST_HEX_BUILD_RULE)

sysLib.o : $(TGT_DIR)/config/CD6011_bsp/sysLib.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(TGT_DIR)/config/CD6011_bsp/sysLib.c -o $@

romcard_vxWorks_st_512.hex: depend.$(BSP_NAME) romcard.o vxWorks.st_rom
	- @ $(RM) $@
	$(LD) -o romcard -X -N -e _romcard romcard.o
	$(ROMSIZEPROG) -b 7fe00 vxWorks.st_rom
	$(BINHEX) -a 0 vxWorks.st_rom | $(SED) -e "/S9/d" > $@
	$(BINHEX) -a 7fe00 -b romcard >> $@
	- @ $(RM) romcard.o romcard
	$(POST_HEX_BUILD_RULE)

sysALib.o : $(TGT_DIR)/config/CD6011_bsp/sysALib.s
	$(AS) $(OPTION_OBJECT_ONLY) $(CFLAGS_AS) $(CFLAGS_AS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(TGT_DIR)/config/CD6011_bsp/sysALib.s -o $@

bootrom.pxe: bootrom.bin pxeBoot.bin
	cat pxeBoot.bin bootrom.bin > bootrom.pxe

#   vxWorks.st_rom	- bootable vxWorks.st(compressed): upper mem

prjConfig.o : $(PRJ_DIR)/prjConfig.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/prjConfig.c -o $@


src_build :

src_depend :

$(PRJ_FULL_PATH)/compObjs.lst : $(PRJ_MAKEFILE)
	@ $(RM) $@
	@ touch $@

src_clean :
	@ $(RM) compObjs.lst
