/* prjParams.h - dynamically generated configuration header */


/*
GENERATED: Sun Oct 30 10:48:30 +0800 2016
DO NOT EDIT - file is regenerated whenever the project changes
*/

#ifndef INCprjParamsh
#define INCprjParamsh


/*** INCLUDED COMPONENTS ***/

#define DRV_KBD_I8042
#define DRV_NVRAM_FILE
#define DRV_SIO_NS16550
#define DRV_TIMER_I8253
#define DRV_VGA_M6845
#define INCLUDE_ANSI_ABORT
#define INCLUDE_ANSI_ABS
#define INCLUDE_ANSI_ASSERT
#define INCLUDE_ANSI_ATOF
#define INCLUDE_ANSI_BSEARCH
#define INCLUDE_ANSI_CTYPE
#define INCLUDE_ANSI_LOCALE
#define INCLUDE_ANSI_LONGJMP
#define INCLUDE_ANSI_MATH
#define INCLUDE_ANSI_MEMCHR
#define INCLUDE_ANSI_MEMCMP
#define INCLUDE_ANSI_MEMCPY
#define INCLUDE_ANSI_MEMMOVE
#define INCLUDE_ANSI_MEMSET
#define INCLUDE_ANSI_STDIO
#define INCLUDE_ANSI_STDIO_EXTRA
#define INCLUDE_ANSI_STDLIB
#define INCLUDE_ANSI_STDLIB_NUMBERS
#define INCLUDE_ANSI_STRCASECMP
#define INCLUDE_ANSI_STRCAT
#define INCLUDE_ANSI_STRCMP
#define INCLUDE_ANSI_STRCPY
#define INCLUDE_ANSI_STRDUP
#define INCLUDE_ANSI_STRERROR
#define INCLUDE_ANSI_STRING
#define INCLUDE_ANSI_STRLCPY
#define INCLUDE_ANSI_STRLEN
#define INCLUDE_ANSI_STRNCASECMP
#define INCLUDE_ANSI_STRNCAT
#define INCLUDE_ANSI_STRNCMP
#define INCLUDE_ANSI_STRNCPY
#define INCLUDE_ANSI_STRTOD
#define INCLUDE_ANSI_TIME
#define INCLUDE_APPL_LOG_UTIL
#define INCLUDE_ATOMIC_OPERATORS
#define INCLUDE_AVL_UINT_TREES
#define INCLUDE_BASE_KERNEL
#define INCLUDE_BLIB
#define INCLUDE_BOOT_LINE_INIT
#define INCLUDE_BSP_MACROS
#define INCLUDE_CACHE_ENABLE
#define INCLUDE_CACHE_SUPPORT
#define INCLUDE_CLASS_LIB
#define INCLUDE_CLASS_LIST
#define INCLUDE_COMMON_NET
#define INCLUDE_COPROCESSOR
#define INCLUDE_COPROCESSOR_SHOW
#define INCLUDE_CPU_LIGHT_PWR_MGR
#define INCLUDE_CPU_PWR_MGMT
#define INCLUDE_CTORS_DTORS
#define INCLUDE_DEBUG
#define INCLUDE_DEVICE_MANAGER
#define INCLUDE_DISK_UTIL
#define INCLUDE_DLL
#define INCLUDE_DMA_SYS
#define INCLUDE_DOSFS
#define INCLUDE_DOSFS_CHKDSK
#define INCLUDE_DOSFS_DIR_FIXED
#define INCLUDE_DOSFS_DIR_VFAT
#define INCLUDE_DOSFS_FAT
#define INCLUDE_DOSFS_FMT
#define INCLUDE_DOSFS_MAIN
#define INCLUDE_DOSFS_SHOW
#define INCLUDE_DOSFS_VOL_BIO_BUFFER_SIZE
#define INCLUDE_DRV_STORAGE_INTEL_ICH
#define INCLUDE_DRV_STORAGE_INTEL_ICH_SHOW
#define INCLUDE_EDR_STUB
#define INCLUDE_EDR_SYSDBG_FLAG
#define INCLUDE_EHCI
#define INCLUDE_EHCI_BUS
#define INCLUDE_EHCI_INIT
#define INCLUDE_END
#define INCLUDE_END_COMMON
#define INCLUDE_END_ETHER_HDR
#define INCLUDE_ENV_VARS
#define INCLUDE_ERF
#define INCLUDE_EVENTPOINT_STUB
#define INCLUDE_EXC_HANDLING
#define INCLUDE_EXC_SHOW
#define INCLUDE_EXC_TASK
#define INCLUDE_FLOATING_POINT
#define INCLUDE_FORMATTED_IO
#define INCLUDE_FORMATTED_OUT_BASIC
#define INCLUDE_FP_TYPE
#define INCLUDE_FS_EVENT_UTIL
#define INCLUDE_FS_MONITOR
#define INCLUDE_FTP
#define INCLUDE_GEI825XX_VXB_END
#define INCLUDE_GENERICPHY
#define INCLUDE_GETOPT
#define INCLUDE_GNU_INTRINSICS
#define INCLUDE_HANDLE_SHOW
#define INCLUDE_HASH
#define INCLUDE_HOOKS
#define INCLUDE_HOST_TBL
#define INCLUDE_HWMEM_ALLOC
#define INCLUDE_HW_FP
#define INCLUDE_IFCONFIG
#define INCLUDE_IO_BASIC
#define INCLUDE_IO_FILE_SYSTEM
#define INCLUDE_IO_MISC
#define INCLUDE_IO_POSIX
#define INCLUDE_IO_REMOVABLE
#define INCLUDE_IO_RTP
#define INCLUDE_IO_SYSTEM
#define INCLUDE_IPAIP
#define INCLUDE_IPAIP_GLOBAL_CONFIGS
#define INCLUDE_IPCOM
#define INCLUDE_IPCOM_SHELL_CMD
#define INCLUDE_IPCOM_USE_AUTH
#define INCLUDE_IPCOM_USE_ETHERNET
#define INCLUDE_IPCOM_USE_INET
#define INCLUDE_IPFTPS
#define INCLUDE_IPIFCONFIG_CMD
#define INCLUDE_IPNET
#define INCLUDE_IPNET_IFCONFIG_1
#define INCLUDE_IPNET_LOOPBACK_CONFIG
#define INCLUDE_IPNET_SOCKET
#define INCLUDE_IPNET_STACK
#define INCLUDE_IPNET_USE_LOOPBACK
#define INCLUDE_IPNET_USE_ROUTESOCK
#define INCLUDE_IPNET_USE_SOCK_COMPAT
#define INCLUDE_IPPROXYARP
#define INCLUDE_IPTCP
#define INCLUDE_IPV4
#define INCLUDE_IPWRAP_IFCONFIG
#define INCLUDE_IPWRAP_INETLIB
#define INCLUDE_ISR_DEFER
#define INCLUDE_JOB_QUEUE
#define INCLUDE_JOB_TASK
#define INCLUDE_KERNEL
#define INCLUDE_KERNEL_ARCH
#define INCLUDE_LINKBUFPOOL
#define INCLUDE_LOADER
#define INCLUDE_LOADER_CODE
#define INCLUDE_LOGGING
#define INCLUDE_LSTLIB
#define INCLUDE_MBUF_UTIL1
#define INCLUDE_MEMORY_CONFIG
#define INCLUDE_MEM_MGR_BASIC
#define INCLUDE_MEM_MGR_FULL
#define INCLUDE_MEM_MGR_INFO
#define INCLUDE_MII_BUS
#define INCLUDE_MMU_BASIC
#define INCLUDE_MMU_GLOBAL_MAP
#define INCLUDE_MMU_P6_32BIT
#define INCLUDE_MODULE_MANAGER
#define INCLUDE_MSG_Q
#define INCLUDE_MSG_Q_CREATE_DELETE
#define INCLUDE_MSG_Q_EVENTS
#define INCLUDE_MSG_Q_INFO
#define INCLUDE_MUX
#define INCLUDE_MUX2
#define INCLUDE_MUX2_OVER_END
#define INCLUDE_MUXTK
#define INCLUDE_MUXTK_OVER_END
#define INCLUDE_MUX_COMMON
#define INCLUDE_NBIO_LOG
#define INCLUDE_NETBUFLIB
#define INCLUDE_NETBUFPOOL
#define INCLUDE_NETMASK_GET
#define INCLUDE_NETWORK
#define INCLUDE_NET_BOOT
#define INCLUDE_NET_DAEMON
#define INCLUDE_NET_DRV
#define INCLUDE_NET_HOST_SETUP
#define INCLUDE_NET_REM_IO
#define INCLUDE_NON_VOLATILE_RAM
#define INCLUDE_OBJ_INFO
#define INCLUDE_OBJ_LIB
#define INCLUDE_OFFSET_SYMBOLS
#define INCLUDE_OHCI
#define INCLUDE_OHCI_BUS
#define INCLUDE_OHCI_INIT
#define INCLUDE_PARAM_SYS
#define INCLUDE_PCI_BUS
#define INCLUDE_PCI_OLD_CONFIG_ROUTINES
#define INCLUDE_PC_CONSOLE
#define INCLUDE_PENTIUM_PCI
#define INCLUDE_PIPES
#define INCLUDE_PLB_BUS
#define INCLUDE_POOL
#define INCLUDE_POSIX_CLOCKS
#define INCLUDE_POSIX_DIRLIB
#define INCLUDE_POSIX_FS
#define INCLUDE_PTYDRV
#define INCLUDE_Q_FIFO
#define INCLUDE_Q_LIB
#define INCLUDE_Q_PRI_BMAP
#define INCLUDE_Q_PRI_DELTA
#define INCLUDE_Q_PRI_LIST
#define INCLUDE_RAWFS
#define INCLUDE_REBOOT_HOOKS
#define INCLUDE_REMLIB
#define INCLUDE_RNG_BUF
#define INCLUDE_SECURITY
#define INCLUDE_SELECT
#define INCLUDE_SELECT_SUPPORT
#define INCLUDE_SEM_BINARY
#define INCLUDE_SEM_BINARY_CREATE
#define INCLUDE_SEM_COUNTING
#define INCLUDE_SEM_COUNTING_CREATE
#define INCLUDE_SEM_DELETE
#define INCLUDE_SEM_EVENTS
#define INCLUDE_SEM_INFO
#define INCLUDE_SEM_LIB
#define INCLUDE_SEM_MUTEX
#define INCLUDE_SEM_MUTEX_CREATE
#define INCLUDE_SEM_READ_WRITE
#define INCLUDE_SEM_READ_WRITE_CREATE
#define INCLUDE_SHELL
#define INCLUDE_SHELL_CORE
#define INCLUDE_SHELL_INTERP_C
#define INCLUDE_SHELL_VI_MODE
#define INCLUDE_SIGNALS
#define INCLUDE_SIGNAL_ARCH
#define INCLUDE_SIO
#define INCLUDE_SIO_UTILS
#define INCLUDE_SLL
#define INCLUDE_SOCKLIB
#define INCLUDE_SPINLOCK
#define INCLUDE_STANDALONE_SYM_TBL
#define INCLUDE_STDIO
#define INCLUDE_SYM_TBL
#define INCLUDE_SYM_TBL_INIT
#define INCLUDE_SYM_TBL_SHOW
#define INCLUDE_SYSCLK_INIT
#define INCLUDE_SYSCTL
#define INCLUDE_SYSHW_INIT
#define INCLUDE_SYSHW_INIT2
#define INCLUDE_SYS_START
#define INCLUDE_TASK_CREATE_DELETE
#define INCLUDE_TASK_CREATE_HOOKS
#define INCLUDE_TASK_HOOKS
#define INCLUDE_TASK_INFO
#define INCLUDE_TASK_LIST
#define INCLUDE_TASK_RESTART
#define INCLUDE_TASK_SHOW
#define INCLUDE_TASK_SWAP_HOOKS
#define INCLUDE_TASK_SWITCH_HOOKS
#define INCLUDE_TASK_UTIL
#define INCLUDE_TASK_VARS
#define INCLUDE_THERM_MONITOR
#define INCLUDE_TIMER_SYS
#define INCLUDE_TIMER_SYS_DELAY
#define INCLUDE_TIMEX
#define INCLUDE_TIP
#define INCLUDE_TTY_DEV
#define INCLUDE_TYLIB
#define INCLUDE_UHCI
#define INCLUDE_UHCI_BUS
#define INCLUDE_UHCI_INIT
#define INCLUDE_UNLOADER
#define INCLUDE_USB
#define INCLUDE_USB_GEN2_HELPER
#define INCLUDE_USB_GEN2_STORAGE
#define INCLUDE_USB_GEN2_STORAGE_INIT
#define INCLUDE_USB_INIT
#define INCLUDE_USER_APPL
#define INCLUDE_VXBUS
#define INCLUDE_VXBUS_ACTIVATE
#define INCLUDE_VXBUS_DEVICE_CONNECT
#define INCLUDE_VXBUS_DEV_INIT
#define INCLUDE_VXBUS_INIT
#define INCLUDE_VXB_SYS_CLK
#define INCLUDE_VXEVENTS
#define INCLUDE_VXMEMPROBE_INIT
#define INCLUDE_VXMUX_MBLK
#define INCLUDE_VXMUX_NULLBUFPOOL
#define INCLUDE_VX_TRADITIONAL_SCHEDULER
#define INCLUDE_WATCHDOGS
#define INCLUDE_WATCHDOGS_CREATE_DELETE
#define INCLUDE_WB_RUNTIME_SUPPORT
#define INCLUDE_WDB
#define INCLUDE_WDB_BANNER
#define INCLUDE_WDB_BP
#define INCLUDE_WDB_BP_SYNC
#define INCLUDE_WDB_COMM_END
#define INCLUDE_WDB_CTXT
#define INCLUDE_WDB_DIRECT_CALL
#define INCLUDE_WDB_EVENTPOINTS
#define INCLUDE_WDB_EVENTS
#define INCLUDE_WDB_EXC_NOTIFY
#define INCLUDE_WDB_EXIT_NOTIFY
#define INCLUDE_WDB_FUNC_CALL
#define INCLUDE_WDB_GOPHER
#define INCLUDE_WDB_KERNEL_INIT_DONE
#define INCLUDE_WDB_MDL_SYM_SYNC
#define INCLUDE_WDB_MEM
#define INCLUDE_WDB_POST_KERNEL_INIT
#define INCLUDE_WDB_REG
#define INCLUDE_WDB_START_NOTIFY
#define INCLUDE_WDB_SYS
#define INCLUDE_WDB_SYS_REG
#define INCLUDE_WDB_TASK
#define INCLUDE_WDB_TASK_BP
#define INCLUDE_WDB_TASK_HOOKS
#define INCLUDE_WDB_TASK_REG
#define INCLUDE_WDB_USER_EVENT
#define INCLUDE_WDB_VIO
#define INCLUDE_WDB_VIO_LIB
#define INCLUDE_XBD
#define INCLUDE_XBD_BLK_DEV
#define INCLUDE_XBD_PART_LIB
#define INIT_HWMEMPOOL_GLOBAL
#define VXBUS_TABLE_CONFIG
#undef INCLUDE_PROTECT_TEXT
#undef INCLUDE_PROTECT_VEC_TABLE
#undef INCLUDE_PCI_PARAMS
#undef INCLUDE_VME_PARAMS
#undef INCLUDE_PCMCIA
#undef INCLUDE_SCSI
#undef INCLUDE_POWER_MGMT_CPU_BSP_SUPPORT
#undef INCLUDE_LPT
#undef INCLUDE_FD
#undef INCLUDE_IDE
#undef INCLUDE_ATA
#undef INCLUDE_AUX_CLK
#undef INCLUDE_TIMESTAMP
#undef INCLUDE_SIO_POLL
#undef INCLUDE_AMP_CPU_01
#undef INCLUDE_AMP_CPU_00
#undef INCLUDE_LOCK_TEXT_SECTION
#undef INCLUDE_PAGE_SIZE_OPTIMIZATION
#undef INCLUDE_CPU_SLEEP_MODE_OFF
#undef INCLUDE_CPU_SLEEP_MODE_SHORT
#undef INCLUDE_CPU_SLEEP_MODE_LONG
#undef INCLUDE_AIM_MMU_MEM_POOL_CONFIG
#undef INCLUDE_AIM_MMU_CONFIG
#undef INCLUDE_AIM_MMU_PT_PROTECTION
#undef INCLUDE_MMU_OPTIMIZE
#undef INCLUDE_TYCODRV_5_2
#undef INCLUDE_SW_FP
#undef INCLUDE_CNS
#undef INCLUDE_WINDMANAGE_SNMP_AGENTX_COMMONCORE
#undef INCLUDE_WINDMANAGE_SNMP_AGENTX_MASTERCORE
#undef INCLUDE_WINDMANAGE_SNMP_AGENTX_SUBAGENTCORE
#undef INCLUDE_WINDMANAGE_SNMP_CORE
#undef INCLUDE_WINDMANAGE_SNMP_V3CORE
#undef INCLUDE_HRFS
#undef INCLUDE_HRFS_READONLY
#undef INCLUDE_CDROMFS
#undef INCLUDE_XBD_TRANS
#undef INCLUDE_XBD_RAMDRV
#undef INCLUDE_HRFS_DEFAULT_WRITE_MODE
#undef INCLUDE_HRFS_HISPEED_WRITE_MODE
#undef INCLUDE_HRFS_ACCESS_TIMESTAMP
#undef INCLUDE_HRFS_FORMAT
#undef INCLUDE_HRFS_CHKDSK
#undef INCLUDE_MIB2_ALL
#undef INCLUDE_MIB2_ICMP
#undef INCLUDE_MIB2_IF
#undef INCLUDE_MIB2_IFMGT
#undef INCLUDE_MIB2_IP
#undef INCLUDE_MIB2_SYSTEM
#undef INCLUDE_MIB2_TCP
#undef INCLUDE_MIB2_UDP
#undef INCLUDE_SSI
#undef INCLUDE_SNMP_DYNAMIC_INIT
#undef INCLUDE_SNMP_STATIC_INIT
#undef INCLUDE_DSI_DYNAMIC_INIT
#undef INCLUDE_UN_COMP
#undef INCLUDE_WM_SNMP_INIT
#undef INCLUDE_VXCPULIB
#undef INCLUDE_PROCFS
#undef INCLUDE_CBIO
#undef INCLUDE_DISK_PART
#undef INCLUDE_CHECKSUM
#undef INCLUDE_TLS_LOADER_SUPPORT
#undef INCLUDE_BMPLIB
#undef INCLUDE_CPLUS
#undef INCLUDE_CPLUS_LANG
#undef INCLUDE_DIAB_INTRINSICS
#undef INCLUDE_NO_INTRINSICS
#undef INCLUDE_CPLUS_IOSTREAMS
#undef INCLUDE_POSIX_ADVISORY_FILE_LOCKING
#undef INCLUDE_POSIX_AIO
#undef INCLUDE_POSIX_AIO_SYSDRV
#undef INCLUDE_POSIX_FTRUNC
#undef INCLUDE_POSIX_MEM
#undef INCLUDE_POSIX_MQ
#undef INCLUDE_POSIX_PTHREADS
#undef INCLUDE_POSIX_SCHED
#undef INCLUDE_POSIX_SEM
#undef INCLUDE_POSIX_SIGNALS
#undef INCLUDE_POSIX_TIMERS
#undef INCLUDE_SIGEVENT
#undef INCLUDE_OBJ_OPEN
#undef INCLUDE_TASK_OPEN
#undef INCLUDE_POSIX_TIMER_SHOW
#undef INCLUDE_SHOW_ROUTINES
#undef INCLUDE_RTP_DEBUG_COMMAND
#undef INCLUDE_RTP
#undef INCLUDE_CLASS_SHOW
#undef INCLUDE_MEM_SHOW
#undef INCLUDE_VM_SHOW
#undef INCLUDE_MSG_Q_SHOW
#undef INCLUDE_POSIX_AIO_SHOW
#undef INCLUDE_POSIX_MQ_SHOW
#undef INCLUDE_POSIX_SEM_SHOW
#undef INCLUDE_SEM_SHOW
#undef INCLUDE_STDIO_SHOW
#undef INCLUDE_TASK_HOOKS_SHOW
#undef INCLUDE_WATCHDOGS_SHOW
#undef INCLUDE_TRIGGER_SHOW
#undef INCLUDE_RBUFF_SHOW
#undef INCLUDE_DATACOLLECTOR_SHOW
#undef INCLUDE_ATA_SHOW
#undef INCLUDE_PCI_CFGSHOW
#undef INCLUDE_HW_FP_SHOW
#undef INCLUDE_EDR_SHOW
#undef INCLUDE_ISR_SHOW
#undef INCLUDE_POOL_SHOW
#undef INCLUDE_OBJECT_SHOW
#undef INCLUDE_TRIGGERING
#undef INCLUDE_RBUFF
#undef INCLUDE_EDR_ERRLOG
#undef INCLUDE_SPY
#undef INCLUDE_SIMPLE_BANNER
#undef INCLUDE_ISR_OBJECTS
#undef INCLUDE_OBJ_OWNERSHIP
#undef INCLUDE_SEM_EXCHANGE
#undef INCLUDE_TASK_ROTATE
#undef INCLUDE_TLS
#undef INCLUDE_EDR_PM
#undef INCLUDE_HOOK_SHOW
#undef INCLUDE_MEM_ALLOT
#undef INCLUDE_CPLUS_DEMANGLER
#undef INCLUDE_SC_POSIX
#undef INCLUDE_PX_SCHED_DEF_POLICIES
#undef INCLUDE_POSIX_PTHREAD_SCHEDULER
#undef INCLUDE_PX_SCHED_SPORADIC_POLICY
#undef INCLUDE_CUSTOM_SCHEDULER
#undef INCLUDE_VX_NATIVE_SCHEDULER
#undef INCLUDE_KERNEL_HARDENING
#undef INCLUDE_PROTECT_TASK_STACK
#undef INCLUDE_TASK_STACK_NO_EXEC
#undef INCLUDE_RAM_DISK
#undef INCLUDE_RAMDRV
#undef INCLUDE_MEMDRV
#undef INCLUDE_ROMFS
#undef INCLUDE_VRFS
#undef INCLUDE_UTF
#undef INCLUDE_STRING_SEARCH
#undef INCLUDE_WINDVIEW
#undef INCLUDE_WINDVIEW_CLASS
#undef INCLUDE_WVNETD
#undef INCLUDE_WVUPLOAD_FILE
#undef INCLUDE_WVUPLOAD_SOCK
#undef INCLUDE_WVUPLOAD_TSFSSOCK
#undef INCLUDE_WDB_TSFS
#undef INCLUDE_SYS_TIMESTAMP
#undef INCLUDE_USER_TIMESTAMP
#undef INCLUDE_SEQ_TIMESTAMP
#undef INCLUDE_SV_DATACOLLECTOR
#undef INCLUDE_DATACOLLECTOR
#undef INCLUDE_EVENTPOINT
#undef INCLUDE_WV_BUFF_USER
#undef INCLUDE_POSIX_TRACE
#undef INCLUDE_POSIX_TRACE_TIMESTAMP
#undef INCLUDE_TRIG_DATACOLLECTOR
#undef INCLUDE_SLL_CREATE_DELETE
#undef INCLUDE_DLL_CREATE_DELETE
#undef INCLUDE_Q_FIFO_CREATE_DELETE
#undef INCLUDE_Q_PRI_LIST_CREATE_DELETE
#undef INCLUDE_Q_PRI_BMAP_CREATE_DELETE
#undef INCLUDE_Q_PRI_DELTA_CREATE_DELETE
#undef INCLUDE_Q_CREATE_DELETE
#undef INCLUDE_AVL_TREES
#undef INCLUDE_PROTECT_INTERRUPT_STACK
#undef INCLUDE_DEBUG_KPRINTF
#undef INCLUDE_DEBUG_KPUTS
#undef INCLUDE_DEBUG_KWRITE_SIO
#undef INCLUDE_DEBUG_KWRITE_USER
#undef INCLUDE_SYSCTL_CLI
#undef INCLUDE_WVTIPC
#undef INCLUDE_SEM_OPEN
#undef INCLUDE_MSG_Q_OPEN
#undef INCLUDE_TIMER_OPEN
#undef INCLUDE_SM_OBJ
#undef INCLUDE_DOSFS_CACHE
#undef INCLUDE_SCSI_DOSFS
#undef INCLUDE_TFFS
#undef INCLUDE_TFFS_MOUNT
#undef INCLUDE_CORE_DUMP
#undef INCLUDE_AF_MIPC_SOCKETS
#undef INCLUDE_DSI_STATIC_INIT
#undef INCLUDE_USB_KEYBOARD_INIT
#undef INCLUDE_SPINLOCK_ISR_ND
#undef INCLUDE_SPINLOCK_ND_TIMED
#undef INCLUDE_WDB_DPRINTF
#undef INCLUDE_WDB_RTP
#undef INCLUDE_WDB_RTP_BP
#undef INCLUDE_WDB_RTP_CONTROL
#undef INCLUDE_WDB_COMM_SERIAL
#undef INCLUDE_WDB_COMM_TYCODRV_5_2
#undef INCLUDE_WDB_COMM_NETWORK
#undef INCLUDE_WDB_COMM_VTMD
#undef INCLUDE_WDB_COMM_PIPE
#undef INCLUDE_WDB_COMM_TIPC
#undef INCLUDE_WDB_COMM_MIPC
#undef INCLUDE_WDB_COMM_CUSTOM
#undef INCLUDE_NET_INIT_SKIP
#undef INCLUDE_TIPC
#undef INCLUDE_MIPC_SM
#undef INCLUDE_WDB_DWARF_EXPR_TEST
#undef INCLUDE_WDB_PRE_KERNEL_INIT
#undef INCLUDE_RTP_APPL_USER
#undef INCLUDE_RTP_SHOW
#undef INCLUDE_RTP_HOOKS
#undef INCLUDE_SHARED_DATA
#undef INCLUDE_SHARED_DATA_SHOW
#undef INCLUDE_SHL
#undef INCLUDE_SHL_SHOW
#undef INCLUDE_RTP_SHELL_CMD
#undef INCLUDE_RTP_SHOW_SHELL_CMD
#undef INCLUDE_SHL_SHELL_CMD
#undef INCLUDE_RTP_POSIX_PSE52
#undef INCLUDE_POSIX_THREAD_CPUTIME
#undef INCLUDE_POSIX_SHM
#undef INCLUDE_POSIX_MAPPED_FILES
#undef INCLUDE_SHELL_EMACS_MODE
#undef INCLUDE_SHELL_HISTORY_FILE
#undef INCLUDE_STAT_SYM_TBL
#undef INCLUDE_NET_SYM_TBL
#undef INCLUDE_SC_SOCKLIB
#undef INCLUDE_NFS2_CLIENT
#undef INCLUDE_CORE_NFS_CLIENT
#undef INCLUDE_NFS3_CLIENT
#undef INCLUDE_NFS_CLIENT_ALL
#undef INCLUDE_RPC
#undef INCLUDE_NFS_MOUNT_ALL
#undef INCLUDE_NFS2_SERVER
#undef INCLUDE_CORE_NFS_SERVER
#undef INCLUDE_NFS_SERVER_INSTALL
#undef INCLUDE_NFS3_SERVER
#undef INCLUDE_NFS_SERVER_ALL
#undef INCLUDE_CACHE_COMPACT_DMA_SUPPORT
#undef INCLUDE_LOADER_HOOKS
#undef INCLUDE_BOOT_APP
#undef INCLUDE_BOOT_ELF
#undef INCLUDE_BOOT_END
#undef INCLUDE_BOOT_EXC_HANDLER
#undef INCLUDE_BOOT_FTP_LOADER
#undef INCLUDE_BOOT_INIT
#undef INCLUDE_BOOT_MEM_CMDS
#undef INCLUDE_BOOT_NETWORK
#undef INCLUDE_BOOT_SHELL
#undef INCLUDE_BOOT_RSH_LOADER
#undef INCLUDE_BOOT_TFTP_LOADER
#undef INCLUDE_ETHERNET
#undef INCLUDE_GTF
#undef INCLUDE_GTF_TIMER_START
#undef INCLUDE_INETLIB
#undef INCLUDE_IPATTACH
#undef INCLUDE_NET_POOL
#undef INCLUDE_TFTP_CLIENT
#undef INCLUDE_XDR
#undef INCLUDE_GETSERVBYNAME
#undef INCLUDE_RTP_APPL_INIT_BOOTLINE
#undef INCLUDE_SHELL_INTERP_CMD
#undef INCLUDE_STARTUP_SCRIPT
#undef INCLUDE_ARP_API
#undef INCLUDE_IPDHCPC
#undef INCLUDE_GETADDRINFO
#undef INCLUDE_GETNAMEINFO
#undef INCLUDE_GETNETBYNAME
#undef INCLUDE_NETSTAT
#undef INCLUDE_NET_SYSCTL
#undef INCLUDE_ROUTECMD
#undef INCLUDE_IPTELNETS
#undef INCLUDE_SYSCALL_HOOKS
#undef INCLUDE_MEM_RTP
#undef INCLUDE_SC_KERNEL
#undef INCLUDE_SC_IOS
#undef INCLUDE_SC_MMAN
#undef INCLUDE_RTP_ARCH
#undef INCLUDE_SC_SD
#undef INCLUDE_SC_SHL
#undef INCLUDE_RTP_SHELL_C
#undef INCLUDE_RTP_APPL_INIT_STRING
#undef INCLUDE_RTP_APPL_INIT_CMD_SHELL_SCRIPT
#undef INCLUDE_RTP_DEBUG
#undef INCLUDE_SHELL_BANNER
#undef INCLUDE_HW_FP_MREGS
#undef INCLUDE_SM_COMMON
#undef INCLUDE_SM_AND_DSHM
#undef INCLUDE_SM_AND_MIPC
#undef INCLUDE_SM_NET
#undef INCLUDE_SM_NET_SHOW
#undef INCLUDE_SMEND
#undef INCLUDE_SC_SYSCTL
#undef INCLUDE_SYSCTL_HW
#undef INCLUDE_VXTESTV2
#undef INCLUDE_VXTESTV2_LF_DRIVER
#undef INCLUDE_VXTESTV2_SF_DRIVER
#undef INCLUDE_VXTESTV2_SF_DRIVER_CALLS
#undef INCLUDE_VXTESTV2_WDB
#undef INCLUDE_VXTESTV2_SHELL
#undef INCLUDE_VXTESTV2_SCALE
#undef INCLUDE_VXTESTV2_EMBEDDED
#undef INCLUDE_VXTESTV2_AUTORUN
#undef INCLUDE_VXTESTV2_SYSPARAMS
#undef INCLUDE_VXTESTV2_POSIX_FS
#undef INCLUDE_TM_CPCLIB
#undef INCLUDE_TM_SPINLOCKLIB
#undef INCLUDE_TM_SPINLOCK_ISR_ND_LIB
#undef INCLUDE_TM_VXATOMICLIB
#undef INCLUDE_TM_CACHELIB
#undef INCLUDE_TM_CACHELIB_MALLOC
#undef INCLUDE_TM_INTARCHLIB
#undef INCLUDE_TM_TASKLIB
#undef INCLUDE_TM_ADRSPACELIB
#undef INCLUDE_TM_DBGLIB
#undef INCLUDE_TM_ISRLIB
#undef INCLUDE_TM_KERNELLIB
#undef INCLUDE_TM_SEMBLIB
#undef INCLUDE_TM_SEMCLIB
#undef INCLUDE_TM_SEMLIBINLINE
#undef INCLUDE_TM_SEMMLIB
#undef INCLUDE_TM_SEMRWLIB
#undef INCLUDE_TM_SYSCALLLIB
#undef INCLUDE_TM_TASKCREATELIB
#undef INCLUDE_TM_TASKHOOKLIB
#undef INCLUDE_TM_TASKRESTARTLIB
#undef INCLUDE_TM_VMTEST
#undef INCLUDE_TM_VXCPULIB
#undef INCLUDE_TM_BSPAPI
#undef INCLUDE_TM_MODEL
#undef INCLUDE_TM_SYSCLOCK
#undef INCLUDE_TM_AUXCLOCK
#undef INCLUDE_TM_NVRAM
#undef INCLUDE_TM_TIMESTAMP
#undef INCLUDE_TM_BOOT_APP
#undef INCLUDE_BOOT_TEST_FUNCS
#undef INCLUDE_BOOT_RAM_IMAGE
#undef INCLUDE_TM_FFSLIB
#undef INCLUDE_TM_FSINITTESTS
#undef INCLUDE_TM_FSTESTS
#undef INCLUDE_TM_ATADRV
#undef INCLUDE_TM_IOBASICLIB
#undef INCLUDE_TM_LOGINLIB
#undef INCLUDE_TM_ENVLIB
#undef INCLUDE_TM_HASHLIB
#undef INCLUDE_TM_ANSICTYPE
#undef INCLUDE_TM_ANSISETJMP
#undef INCLUDE_TM_ANSISTDARG
#undef INCLUDE_TM_ANSISTDLIB
#undef INCLUDE_TM_BLIB
#undef INCLUDE_TM_CLOCKLIB
#undef INCLUDE_TM_MEMLIB
#undef INCLUDE_TM_MEMDRVLIB
#undef INCLUDE_TM_MSGQLIB
#undef INCLUDE_TM_SEMSHOW
#undef INCLUDE_TM_SIGLIB
#undef INCLUDE_TM_SYMLIB
#undef INCLUDE_TM_PGPOOLPHYSLIB
#undef INCLUDE_PG_POOL_LIB
#undef INCLUDE_TM_PGPOOLVIRTLIB
#undef INCLUDE_TM_MQPXLIB
#undef INCLUDE_TM_NETBUFLIB
#undef INCLUDE_TM_OBJLIB
#undef INCLUDE_TM_PGMGRLIB
#undef INCLUDE_TM_PRIINHERIT
#undef INCLUDE_TM_SALLIB
#undef INCLUDE_SAL_COMMON
#undef INCLUDE_TM_SALSTRESSLIB
#undef INCLUDE_TM_TASKOPEN
#undef INCLUDE_TM_MEMPARTLIB
#undef INCLUDE_VM_RTP
#undef INCLUDE_TM_POOLLIB
#undef INCLUDE_TM_PXTRACEEVENTID
#undef INCLUDE_TM_HOOKLIB
#undef INCLUDE_TM_WORKQLIB
#undef INCLUDE_TM_WDCREATELIB
#undef INCLUDE_TM_ANSITIME
#undef INCLUDE_TM_TASKSHOW
#undef INCLUDE_TM_PIPEDRV
#undef INCLUDE_TM_PIPEDRV2
#undef INCLUDE_TM_TASKVARLIB
#undef INCLUDE_TM_PMLIB
#undef INCLUDE_TM_TASKINFO
#undef INCLUDE_TM_SOCKLIB
#undef INCLUDE_TM_MEMPARTFUNC
#undef INCLUDE_TM_PTHREADLIB
#undef INCLUDE_TM_SHMLIB
#undef INCLUDE_TM_WINDSTRESSTEST
#undef INCLUDE_TM_HEAPSTRESSTEST
#undef INCLUDE_TM_MACROTEST
#undef INCLUDE_TM_PINGLIB
#undef INCLUDE_PING
#undef INCLUDE_TM_ERRNOLIB_SMP
#undef INCLUDE_TM_COMPS
#undef INCLUDE_TM_USBSHOW
#undef INCLUDE_USB_MS_BULKONLY
#undef INCLUDE_USB_MS_BULKONLY_INIT
#undef INCLUDE_TM_VXBTEST
#undef INCLUDE_VXBUS_SHOW
#undef INCLUDE_TM_VXBPCIACCESS
#undef INCLUDE_TM_VXBVIRTACCESS
#undef INCLUDE_TM_VXBPARAMSYS
#undef INCLUDE_TM_VXBTESTDMABUFFER
#undef INCLUDE_TM_VXBTESTDMALIB
#undef INCLUDE_TM_VXBTIMERLIB
#undef INCLUDE_TM_VXBTESTSIO
#undef INCLUDE_TM_VXBTIMERDRIVER
#undef INCLUDE_WDB_PROXY
#undef INCLUDE_WDB_PROXY_UDP
#undef INCLUDE_WDB_PROXY_TIPC
#undef INCLUDE_WDB_PROXY_MIPC
#undef INCLUDE_SAL_CLIENT
#undef INCLUDE_SAL_SERVER
#undef INCLUDE_SNS_SHOW
#undef INCLUDE_SNS
#undef INCLUDE_SNS_RTP
#undef INCLUDE_SNS_MP
#undef INCLUDE_SNS_MP_RTP
#undef INCLUDE_SNS_COMMON
#undef INCLUDE_SNS_RTP_HOOK
#undef INCLUDE_UN
#undef INCLUDE_DSI_SOCKET
#undef INCLUDE_DSI_POOL
#undef INCLUDE_UN_SHOW
#undef INCLUDE_UN_COMP_SHOW
#undef INCLUDE_CORE_DUMP_SHOW
#undef INCLUDE_CORE_DUMP_MEM_FILTER
#undef INCLUDE_CORE_DUMP_MEM_POOL
#undef INCLUDE_CORE_DUMP_COMPRESS
#undef INCLUDE_CORE_DUMP_COMPRESS_RLE
#undef INCLUDE_CORE_DUMP_COMMON_COMPRESS_ZLIB
#undef INCLUDE_CORE_DUMP_COMMON_COMPRESS_RLE
#undef INCLUDE_CORE_DUMP_UTIL
#undef INCLUDE_CORE_DUMP_MEM
#undef INCLUDE_CORE_DUMP_RAW_DEV
#undef INCLUDE_CORE_DUMP_RTP
#undef INCLUDE_CORE_DUMP_RTP_COMPRESS_ZLIB
#undef INCLUDE_CORE_DUMP_RTP_COMPRESS_RLE
#undef INCLUDE_CORE_DUMP_RTP_FS
#undef INCLUDE_MEM_EDR
#undef INCLUDE_MEM_EDR2
#undef INCLUDE_MEM_EDR_RTC
#undef INCLUDE_MEM_EDR_SHOW
#undef INCLUDE_MEM_EDR_RTP_SHOW
#undef INCLUDE_ADR_SPACE_LIB
#undef INCLUDE_PG_MGR_LIB
#undef INCLUDE_PG_POOL_VIRT_LIB
#undef INCLUDE_PG_POOL_PHYS_LIB
#undef INCLUDE_ADR_SPACE_SHOW
#undef INCLUDE_PG_MGR_SHOW
#undef INCLUDE_PG_POOL_SHOW
#undef INCLUDE_VM_INVTBL
#undef INCLUDE_MAPPED_FILES_SHOW
#undef INCLUDE_DISK_UTIL_SHELL_CMD
#undef INCLUDE_EDR_SHELL_CMD
#undef INCLUDE_TASK_SHELL_CMD
#undef INCLUDE_DEBUG_SHELL_CMD
#undef INCLUDE_SYM_SHELL_CMD
#undef INCLUDE_VM_SHOW_SHELL_CMD
#undef INCLUDE_ADR_SPACE_SHELL_CMD
#undef INCLUDE_SHARED_DATA_SHOW_SHELL_CMD
#undef INCLUDE_MAPPED_FILES_SHOW_SHELL_CMD
#undef INCLUDE_MEM_EDR_SHELL_CMD
#undef INCLUDE_MEM_EDR_RTP_SHELL_CMD
#undef INCLUDE_MODULE_SHELL_CMD
#undef INCLUDE_UNLOADER_SHELL_CMD
#undef INCLUDE_HISTORY_FILE_SHELL_CMD
#undef INCLUDE_CAN_NETWORK_INIT
#undef INCLUDE_WNCAN_SHOW
#undef INCLUDE_WNCAN_DEVIO
#undef INCLUDE_ESD_CAN_PCI_200
#undef INCLUDE_PPC5XX_WNCAN
#undef INCLUDE_MCF5282_WNCAN
#undef INCLUDE_ESD_CAN_PCI_200_2
#undef INCLUDE_ESD_CAN_PC104_200
#undef INCLUDE_MSMCAN_PC104
#undef INCLUDE_MPC5200_WNCAN
#undef INCLUDE_TOLAPAI_CAN
#undef INCLUDE_CCI_COREAPI
#undef INCLUDE_CCI_PERFORMANCE
#undef INCLUDE_CCI_VALIDATE
#undef INCLUDE_AR521X_SECPOL_TSN
#undef INCLUDE_AR521X_SECPOL_WPA
#undef INCLUDE_AR521X_SECPOL_11i
#undef INCLUDE_CCI_DEFAULT_PROVIDER
#undef INCLUDE_IPCRYPTO
#undef INCLUDE_CCI_IMPORT_AES
#undef INCLUDE_CCI_IMPORT_AESKW
#undef INCLUDE_CCI_IMPORT_DES
#undef INCLUDE_CCI_IMPORT_BLOWFISH
#undef INCLUDE_CCI_IMPORT_CAST
#undef INCLUDE_CCI_IMPORT_RC4
#undef INCLUDE_CCI_IMPORT_RC4TKIP
#undef INCLUDE_CCI_IMPORT_NULL
#undef INCLUDE_CCI_IMPORT_PRNG
#undef INCLUDE_CCI_IMPORT_HASH_CRC32
#undef INCLUDE_CCI_IMPORT_HASH_MD2
#undef INCLUDE_CCI_IMPORT_HASH_MD4
#undef INCLUDE_CCI_IMPORT_HASH_MD5
#undef INCLUDE_CCI_IMPORT_HASH_SHA1
#undef INCLUDE_CCI_IMPORT_HASH_SHA224
#undef INCLUDE_CCI_IMPORT_HASH_SHA256
#undef INCLUDE_CCI_IMPORT_HASH_SHA384
#undef INCLUDE_CCI_IMPORT_HASH_SHA512
#undef INCLUDE_CCI_IMPORT_HASH_RIP160
#undef INCLUDE_CCI_IMPORT_HASH_RIP128
#undef INCLUDE_CCI_IMPORT_HMAC_MD4
#undef INCLUDE_CCI_IMPORT_HMAC_MD5
#undef INCLUDE_CCI_IMPORT_HMAC_SHA1
#undef INCLUDE_CCI_IMPORT_HMAC_SHA224
#undef INCLUDE_CCI_IMPORT_HMAC_SHA256
#undef INCLUDE_CCI_IMPORT_HMAC_SHA384
#undef INCLUDE_CCI_IMPORT_HMAC_SHA512
#undef INCLUDE_CCI_IMPORT_HMAC_RIP160
#undef INCLUDE_CCI_IMPORT_HMAC_RIP128
#undef INCLUDE_CCI_IMPORT_HMAC_AESXCBC
#undef INCLUDE_CCI_IMPORT_AES_CMAC
#undef INCLUDE_CCI_IMPORT_INTEGER
#undef INCLUDE_CCI_IMPORT_PUBLICKEY_RSA
#undef INCLUDE_CCI_IMPORT_IPSEC_SINGLEPASS
#undef INCLUDE_MPC5121E_WNCAN
#undef INCLUDE_TFFS_SHOW
#undef INCLUDE_MTD_AMD
#undef INCLUDE_MTD_I28F008
#undef INCLUDE_MTD_I28F008BAJA
#undef INCLUDE_MTD_I28F016
#undef INCLUDE_MTD_WAMD
#undef INCLUDE_MTD_CFIAMD
#undef INCLUDE_MTD_CFISCS
#undef INCLUDE_TL_FTL
#undef INCLUDE_TL_SSFDC
#undef INCLUDE_TAR
#undef INCLUDE_DOSFS_PRTMSG_LEVEL
#undef INCLUDE_DOWNLOADABLE_DRIVERS
#undef INCLUDE_VXIPI
#undef INCLUDE_INTCTLR_LIB
#undef INCLUDE_VXB_AUX_CLK
#undef INCLUDE_VXB_TIMESTAMP
#undef INCLUDE_TIMER_STUB
#undef INCLUDE_SYNOPSYSHCI_INIT
#undef INCLUDE_TIMER_SYS_SHOW
#undef INIT_HWMEMPOOL_IN_BSP
#undef INCLUDE_PCI_BUS_AUTOCONF
#undef INCLUDE_PCI_BUS_SHOW
#undef INCLUDE_VXBUS_SM_SUPPORT
#undef INCLUDE_WRLOAD
#undef INCLUDE_WRLOAD_IMAGE_BUILD
#undef INCLUDE_XBD_CBIO_DEV
#undef INCLUDE_RAPIDIO_BUS
#undef RAPIDIO_BUS_AUTOCONFIG
#undef RAPIDIO_BUS_STATIC_PROBE
#undef RAPIDIO_BUS_STATIC_TABLE
#undef INCLUDE_VXB_LEGACY_INTERRUPTS
#undef INCLUDE_BOOT_DELAYED_INIT
#undef INCLUDE_BOOT_MMU_BASIC
#undef INCLUDE_BOOT_EDR_SUPPORT
#undef INCLUDE_NET_BOOT_CONFIG
#undef INCLUDE_BOOT_NET_DEVICES
#undef INCLUDE_BOOT_VXBUS
#undef INCLUDE_BOOT_ETH_MAC_HANDLER
#undef INCLUDE_BOOT_ETH_ADR_SET
#undef INCLUDE_BOOT_DHCPC
#undef INCLUDE_BOOT_FILESYSTEMS
#undef INCLUDE_BOOT_FS_DEVICES
#undef INCLUDE_BOOT_FD_LOADER
#undef INCLUDE_BOOT_USB_FS_LOADER
#undef INCLUDE_BOOT_TSFS_LOADER
#undef INCLUDE_TSFS_BOOT_VIO_CONSOLE
#undef INCLUDE_DSHM
#undef INCLUDE_DSHM_MUX
#undef INCLUDE_DSHM_ADAPT
#undef INCLUDE_DSHM_DEBUG
#undef INCLUDE_DSHM_SVC_MNG
#undef INCLUDE_DSHM_MSG_SM
#undef INCLUDE_DSHM_NOWRING
#undef INCLUDE_DSHM_BUS
#undef INCLUDE_DSHM_BUS_PLB
#undef INCLUDE_DSHM_VXPLB
#undef INCLUDE_DSHM_MEM
#undef INCLUDE_DSHM_RW_LOCK
#undef INCLUDE_DSHM_OWRING
#undef INCLUDE_DSHM_SPINLOCK
#undef INCLUDE_DSHM_POW2
#undef INCLUDE_MIPC_UNSUPPORTED
#undef INCLUDE_MIPC_SHOW
#undef INCLUDE_MIPC_DEMO
#undef INCLUDE_AF_MIPC_DEMO
#undef INCLUDE_MND
#undef INCLUDE_MSD
#undef INCLUDE_TIPC_SHOW
#undef INCLUDE_CONFIG_TIPC_SOCKET_API
#undef INCLUDE_TIPC_MEMPOOL
#undef INCLUDE_TIPC_HEND_INIT
#undef INCLUDE_TIPC_DEFINES
#undef INCLUDE_TIPC_NODEBUG
#undef INCLUDE_TIPC_NOSYS_MSGS
#undef INCLUDE_TIPC_NOCFG_SERVICE
#undef INCLUDE_TIPC_NOSOCKET
#undef INCLUDE_USE_LIBTIPC
#undef INCLUDE_BUILD_TIPC_SRC
#undef INCLUDE_TIPC_CONFIG_STR
#undef INCLUDE_TIPC_CONFIG_HOOK_BOOT
#undef INCLUDE_TIPC_CONFIG_HOOK_USER
#undef INCLUDE_TIPC_MEDIA_ETH
#undef INCLUDE_TIPC_IP
#undef INCLUDE_TIPC_ONLY
#undef INCLUDE_TIPC_TS
#undef INCLUDE_TIPC_IS
#undef INCLUDE_VXBUS_END_QCTRL
#undef DRV_RESOURCE_FSLGPIO
#undef DRV_RESOURCE_QORIQQMAN
#undef DRV_RESOURCE_FSLI2C
#undef DRV_TIMER_MIPSR4K
#undef DRV_TIMER_SB1
#undef DRV_TIMER_CN3XXX
#undef INCLUDE_XLR_TIMER
#undef DRV_TIMER_OPENPIC
#undef DRV_RESOURCE_QORIQBMAN
#undef DRV_RESOURCE_QORIQLAW
#undef DRV_RESOURCE_QORIQFMAN
#undef DRV_RESOURCE_QORIQFMAN_SOFTPARSE_ASSEMBLER
#undef DRV_RESOURCE_QORIQFMAN_SOFTPARSE
#undef DRV_PCIBUS_QORIQ_PCIEX
#undef INCLUDE_AN983_VXB_END
#undef INCLUDE_DOT11_TEST
#undef INCLUDE_IPWLAN_CMD
#undef INCLUDE_DOT11_MIB
#undef INCLUDE_IPWLAN_ATHEROS
#undef INCLUDE_AR521X_VXBEND
#undef INCLUDE_AR521X_END
#undef INCLUDE_BCM43XX_END
#undef INCLUDE_BCM43XX_VXBEND
#undef INCLUDE_AR521X_END_ESS
#undef INCLUDE_AR521X_END_IBSS
#undef INCLUDE_AR521X_END_AP
#undef INCLUDE_BRIDGE
#undef INCLUDE_AR521X_AUTH_8021X
#undef INCLUDE_AR521X_AUTH_PSK
#undef INCLUDE_AR521X_AUTH_PSK_PASSPHRASE
#undef INCLUDE_AR521X_CIPH_WEP40
#undef INCLUDE_AR521X_CIPH_WEP104
#undef INCLUDE_AR521X_CIPH_TKIP
#undef INCLUDE_AR521X_CIPH_AES
#undef INCLUDE_IPWLAN_BROADCOM
#undef INCLUDE_BCM43XX_CIPH_TKIP
#undef INCLUDE_BCM43XX_CIPH_AES
#undef INCLUDE_BCM43XX_CIPH_WEP40
#undef INCLUDE_BCM43XX_CIPH_WEP104
#undef INCLUDE_BCM43XX_AUTH_WPA_8021X
#undef INCLUDE_BCM43XX_AUTH_WPA2_8021X
#undef INCLUDE_BCM43XX_AUTH_WPA_PSK
#undef INCLUDE_BCM43XX_AUTH_WPA_PSK_PASSPHRASE
#undef INCLUDE_BCM43XX_AUTH_WPA2_PSK
#undef INCLUDE_BCM43XX_AUTH_WPA2_PSK_PASSPHRASE
#undef INCLUDE_VXB_CPM
#undef INCLUDE_TC3C905_VXB_END
#undef INCLUDE_NE2000_VXB_END
#undef INCLUDE_MOT_ETSEC_HEND
#undef INCLUDE_FCC_VXB_END
#undef INCLUDE_MDIO
#undef INCLUDE_BCM52XXPHY
#undef INCLUDE_MOT_FEC_HEND
#undef INCLUDE_FEC_VXB_END
#undef INCLUDE_FEI8255X_VXB_END
#undef INCLUDE_GT64120A_MF
#undef INCLUDE_GT64120A_PCI
#undef INCLUDE_GT64120A_DMA
#undef INCLUDE_GT64120A_TIMER
#undef INCLUDE_GT64120A_INTCTLR
#undef INCLUDE_GT64120A_SDRAM
#undef INCLUDE_GT64120A_I2O
#undef INCLUDE_GEI_HEND
#undef INCLUDE_GEI825XX_VXB_END2
#undef INCLUDE_END2
#undef INCLUDE_HEND_PARAM_SYS
#undef INCLUDE_HEND_NPT
#undef DRV_I8259VXBPIC
#undef DRV_TIMER_IXP400
#undef DRV_PCIBUS_IXP4XX
#undef INCLUDE_VXB_DMA_END2_IXP4XX_PCI
#undef INCLUDE_AM79C97X_VXB_END
#undef DRV_PCIBUS_M83XX
#undef DRV_PCIBUS_M83XX_EX
#undef DRV_RESOURCE_M85XXCCSR
#undef INCLUDE_M85XX_CPU
#undef DRV_PCIBUS_M85XX
#undef INCLUDE_M85XX_RAPIDIO
#undef INCLUDE_M85XX_RIO_SM_CFG
#undef INCLUDE_GENERICTBIPHY
#undef INCLUDE_BCM54XXPHY
#undef INCLUDE_DM9161PHY
#undef INCLUDE_GEITBIPHY
#undef INCLUDE_ICP175CPHY
#undef INCLUDE_LXT972PHY
#undef INCLUDE_MV88E1X11PHY
#undef INCLUDE_MV88E1113PHY
#undef INCLUDE_RTL8201PHY
#undef INCLUDE_RTL8169PHY
#undef INCLUDE_VSC82XXPHY
#undef DRV_MII_I2C_MDIO
#undef DRV_MII_DTSEC_MDIO
#undef DRV_MII_TGEC_MDIO
#undef INCLUDE_RMI_MDIO
#undef INCLUDE_TSEC_MDIO
#undef INCLUDE_UCC_MDIO
#undef DRV_MII_DTEPHY
#undef INCLUDE_DUMMY_MDIO
#undef INCLUDE_NS83902_VXB_END
#undef INCLUDE_NS8381X_VXB_END
#undef DRV_TIMER_DEC_PPC
#undef INCLUDE_QE_FCC_HEND
#undef INCLUDE_QUICC_ENGINE_UTILS
#undef INCLUDE_RTL8169_VXB_END
#undef INCLUDE_RTL8139_VXB_END
#undef INCLUDE_SBE_VXB_END
#undef INCLUDE_SCC_VXB_END
#undef INCLUDE_MOT_TSEC_HEND
#undef INCLUDE_TSEC_VXB_END
#undef INCLUDE_TSEC_VXB_END2
#undef DRV_SIO_COLDFIRE
#undef DRV_SIO_IXP400
#undef DRV_SIO_SB1
#undef DRV_SIO_PRIMECELL
#undef DRV_SIO_OCTEON
#undef DRV_SIO_M5XXX_PSC
#undef DRV_SIO_IMX
#undef DRV_SIO_DAVINCI
#undef DRV_SIO_AT91
#undef INCLUDE_SYNOPSYSHCI
#undef INCLUDE_PDIUSBD12
#undef INCLUDE_PHILIPS1582
#undef INCLUDE_NET2280
#undef INCLUDE_FSL_TCD
#undef INCLUDE_USB_TARG
#undef INCLUDE_KBD_EMULATOR
#undef INCLUDE_PRN_EMULATOR
#undef INCLUDE_D12_EMULATOR
#undef INCLUDE_MS_EMULATOR
#undef INCLUDE_SER_EMULATOR
#undef INCLUDE_KBD_EMULATOR_INIT
#undef INCLUDE_PRN_EMULATOR_INIT
#undef INCLUDE_MS_EMULATOR_INIT
#undef INCLUDE_SER_EMULATOR_INIT
#undef INCLUDE_USB_GEN2_PRINTER
#undef INCLUDE_USB_GEN2_MOUSE
#undef INCLUDE_USB_GEN2_KEYBOARD
#undef INCLUDE_USB_MOUSE
#undef INCLUDE_USB_KEYBOARD
#undef INCLUDE_USB_PRINTER
#undef INCLUDE_USB_SPEAKER
#undef INCLUDE_USB_PEGASUS_END
#undef INCLUDE_USB_MS_CBI
#undef INCLUDE_SYNOPSYSHCI_BUS
#undef INCLUDE_USB_MOUSE_INIT
#undef INCLUDE_USB_PRINTER_INIT
#undef INCLUDE_USB_SPEAKER_INIT
#undef INCLUDE_USB_MS_CBI_INIT
#undef INCLUDE_USB_PEGASUS_END_INIT
#undef INCLUDE_USB_AUDIO_DEMO
#undef INCLUDE_USB_HEADSET_DEMO
#undef INCLUDE_USB_GEN2_PRINTER_INIT
#undef INCLUDE_USB_GEN2_END_INIT
#undef INCLUDE_USB_GEN2_MOUSE_INIT
#undef INCLUDE_USBTOOL
#undef INCLUDE_USB_GEN2_KEYBOARD_INIT
#undef INCLUDE_USB_GEN2_KEYBOARD_SHELL_ATTACH
#undef INCLUDE_USB_GEN2_KEYBOARD_BOOTSHELL_ATTACH
#undef INCLUDE_USB_GEN2_PEGASUS
#undef INCLUDE_USB_GEN2_DM960X
#undef INCLUDE_USB_GEN2_ASIX
#undef INCLUDE_USB_KEYBOARD_SHELL_ATTACH
#undef INCLUDE_USB_KEYBOARD_BOOTSHELL_ATTACH
#undef DRV_INTCTLR_ADS5121E_CPLD
#undef DRV_TIMER_AMBA
#undef DRV_PCIBUS_ARMAXI
#undef DRV_ARM_GIC
#undef DRV_ARM_MPCORE_TIMER
#undef DRV_VXBEND_AT91EMAC
#undef DRV_INTCTLR_AT91
#undef DRV_TIMER_AT91
#undef INCLUDE_CNS3XXX_VXB_END
#undef DRV_PCIBUS_CNS3XXX_EX
#undef DRV_TIMER_CNS3XXX
#undef DRV_VXBEND_DAVINCI_EMAC
#undef DRV_INTCTLR_DAVINCI
#undef DRV_TIMER_DAVINCI
#undef DRV_VXBEND_DC2114X
#undef DRV_VXBEND_DM9000A
#undef DRV_VXBEND_DTSEC
#undef DRV_EB_GIC
#undef DRV_INTCTLR_EPIC
#undef INCLUDE_ETSEC_VXB_END
#undef INCLUDE_ETSEC_VXB_END2
#undef DRV_FW_FSL_AXE
#undef DRV_DMA_FSL
#undef DRV_STORAGE_FSLSATA
#undef DRV_INTCTLR_I8259
#undef INCLUDE_IPIIX4_MF
#undef INCLUDE_EMAC_VXB_END
#undef INCLUDE_VXB_IBM_MAL
#undef INCLUDE_VXB_IBM_ZMII
#undef INCLUDE_VXB_IBM_RGMII
#undef INCLUDE_VXB_IBM_TAH
#undef DRV_TIMER_IMX31EPIT
#undef DRV_TIMER_IMX31GPT
#undef DRV_INTCTLR_IMX31
#undef INCLUDE_INTCTLR_SHOW
#undef INCLUDE_INTCTLR_DYNAMIC_LIB
#undef INCLUDE_DRV_STORAGE_INTEL_AHCI
#undef INCLUDE_DRV_STORAGE_INTEL_AHCI_SHOW
#undef DRV_DMA_INTEL_EDMA
#undef DRV_MII_INTEL_GCU
#undef DRV_TIMER_IA_TIMESTAMP
#undef DRV_VXBEND_INTELTOPCLIFF
#undef DRV_RESOURCE_INTELTOPCLIFF_IOH
#undef DRV_INTCTLR_IOAPIC
#undef DRV_PCI_VIRTUAL
#undef DRV_INTCTLR_LOAPIC
#undef DRV_TIMER_LOAPIC
#undef DRV_VXBEND_LPC24XXEMAC
#undef DRV_INTCTL_LPC24XX
#undef DRV_TIMER_LPC24XX
#undef DRV_DMA_M512X
#undef INCLUDE_M512XFEC_VXB_END
#undef DRV_MF_M512X_FIFOC
#undef DRV_TIMER_M5XXX_GPT
#undef DRV_TIMER_M85XX
#undef DRV_TIMER_MC146818
#undef DRV_INTCTLR_MIPS
#undef DRV_INTCTLR_MIPS_SBE
#undef DRV_INTCTLR_MIPS_CAV
#undef DRV_INTCTLR_MIPS_XLR
#undef DRV_INTCTLR_MIPS_MT_IPI
#undef DRV_INTCTLR_MPAPIC
#undef INCLUDE_MSC01_PCI
#undef DRV_VXBEND_MYRILANAI
#undef DRV_INTCTLR_OMAP2530
#undef DRV_TIMER_OMAP2530
#undef DRV_DMA_OMAP35XX
#undef DRV_INTCTLR_OMAP35XX
#undef DRV_STORAGE_OMAP35XX_MMCHS
#undef DRV_TIMER_OMAP35XX
#undef DRV_INTCTLR_OMAPL137
#undef DRV_TIMER_PPC405
#undef DRV_TIMER_PPC440
#undef INCLUDE_PPC440GX_PCI
#undef DRV_PCIBUS_PPC4XX_PCI
#undef DRV_PCIBUS_PPC4XX_PCIEX
#undef DRV_INTCTLR_UIC
#undef DRV_TIMER_QUICC_PPC
#undef DRV_INTCTLR_PXA3XXGPIO
#undef DRV_INTCTLR_PXA3XX
#undef DRV_TIMER_PXA3XX
#undef DRV_INTCTLR_QE
#undef DRV_INTCTLR_QUICC
#undef INCLUDE_XLR_GMAC_VXB_END
#undef DRV_VXBEND_XLRXGMAC
#undef DRV_RESOURCE_XLRCPLD
#undef DRV_STORAGE_SI31XX
#undef DRV_STORAGE_SDHC
#undef DRV_SUPERIO_SMCFDC37X
#undef INCLUDE_SMSCLAN9118_VXB_END
#undef INCLUDE_SMSCLAN91C111_VXB_END
#undef DRV_VXBEND_STMSPEAR13XX_GEMAC
#undef DRV_TIMER_STMSPEAR13XX
#undef DRV_VXBEND_TEI82598
#undef DRV_VXBEND2_TEI8259X
#undef DRV_VXBEND_TGEC
#undef DRV_VXBEND_TI_EMAC
#undef INCLUDE_UCC_VXB_END
#undef DRV_INTCTLR_VB
#undef DRV_TIMER_VB
#undef DRV_VXBEND_VIARHINE
#undef DRV_INTCTRL_VIOAPIC
#undef INCLUDE_XLR_FMN
#undef DRV_PCIBUS_XLS_PCIEX
#undef INCLUDE_XLR_PCI
#undef INCLUDE_MVYUKON_VXB_END
#undef INCLUDE_MVYUKONII_VXB_END
#undef INCLUDE_FLASHFX_DRIVER
#undef INCLUDE_FLASHFX_TOOLS
#undef INCLUDE_FLASHFX_TESTS
#undef INCLUDE_FLASHFX_DISK_0
#undef INCLUDE_FLASHFX_DISK_1
#undef INCLUDE_FLASHFX_DISK_2
#undef INCLUDE_FLASHFX_DISK_3
#undef INCLUDE_CPU_UTIL_PWR_MGR
#undef INCLUDE_OSM
#undef INCLUDE_IPCOM_AUTH_1
#undef INCLUDE_IPCOM_AUTH_2
#undef INCLUDE_IPCOM_AUTH_3
#undef INCLUDE_IPCOM_AUTH_4
#undef INCLUDE_IPCOM_AUTH_5
#undef INCLUDE_IPCOM_AUTH_6
#undef INCLUDE_USE_IPCOM_SHELL
#undef INCLUDE_USE_NATIVE_SHELL
#undef INCLUDE_IPCOM_USE_VXSHELL_CMD
#undef INCLUDE_IPCOM_USE_RAM_DISK
#undef INCLUDE_IPCOM_FS_IPCOM
#undef INCLUDE_IPCOM_FS_NATIVE
#undef INCLUDE_IPNET_IFCONFIG_2
#undef INCLUDE_IPNET_IFCONFIG_3
#undef INCLUDE_IPNET_IFCONFIG_4
#undef INCLUDE_IPAIP_INTERFACE_CONFIGS
#undef INCLUDE_IPDNSC
#undef INCLUDE_IPFTPC
#undef INCLUDE_IPRADVD
#undef INCLUDE_IPCOM_USE_INET6
#undef INCLUDE_IPTFTP_COMMON
#undef INCLUDE_IPTFTPC
#undef INCLUDE_IPTFTPS
#undef INCLUDE_IPSNTP_COMMON
#undef INCLUDE_IPSNTPS
#undef INCLUDE_IPSNTPC
#undef INCLUDE_IPSNTPC_API
#undef INCLUDE_IPSNTPS_API
#undef INCLUDE_IPFIREWALL
#undef INCLUDE_IPFIREWALL_CMD
#undef INCLUDE_IPL2TP
#undef INCLUDE_IPCOM_USE_LINK_STUB
#undef INCLUDE_IPNET_USE_PPP
#undef INCLUDE_IPNET_USE_WLAN
#undef INCLUDE_IPNET_USE_SOCKDEV
#undef INCLUDE_IPMIP
#undef INCLUDE_IPMIP4
#undef INCLUDE_IPMIP6
#undef INCLUDE_IPMIPFA
#undef INCLUDE_IPMIPFA_AAA_RADIUS
#undef INCLUDE_IPRADIUS
#undef INCLUDE_IPMIPFA_AAA_DIAMETER
#undef INCLUDE_IPDIAMETERC
#undef INCLUDE_IPMIPFA_PMIPV4
#undef INCLUDE_IPMIPFA_PMIPV4_DHCP
#undef INCLUDE_IPMIPFA_FEATURE_EXTENSION
#undef INCLUDE_IPMIPFA_CMD
#undef INCLUDE_IPMIPHA
#undef INCLUDE_IPMIPHA_AAA_RADIUS
#undef INCLUDE_IPMIPHA_AAA_DIAMETER
#undef INCLUDE_IPMIPHA_FEATURE_EXTENSION
#undef INCLUDE_IPMIPHA_CMD
#undef INCLUDE_IPMIP6HA
#undef INCLUDE_IPMIP6HA_DUAL_STACK
#undef INCLUDE_IPMIP6HA_MOBILE_ROUTER
#undef INCLUDE_IPMIP6HA_MOBILE_ROUTER_DUAL_STACK
#undef INCLUDE_IPMIP6HA_LMA
#undef INCLUDE_IPMIP6HA_LMA_DHCP_SERVER
#undef INCLUDE_IPMIP6HA_LMA_DUAL_STACK
#undef INCLUDE_IPMIP6HA_LMA_DUAL_STACK_DHCP_SERVER
#undef INCLUDE_IPMIP6HA_FEATURE_EXTENSION
#undef INCLUDE_IPMIP6HA_CMD
#undef INCLUDE_IPMIPMN
#undef INCLUDE_IPMIPMN_FEATURE_EXTENSION
#undef INCLUDE_IPMIP6MN
#undef INCLUDE_IPMIP6MN_CMD
#undef INCLUDE_IPMIP6MN_NEMO
#undef INCLUDE_IPMIP6MN_NEMO_RADVD
#undef INCLUDE_IPMIP6MN_DUAL_STACK_NEMO
#undef INCLUDE_IPMIP6MN_DUAL_STACK_NEMO_DHCP_SERVER
#undef INCLUDE_IPMIP6MN_IPSEC
#undef INCLUDE_IPMIP6MN_DUAL_STACK
#undef INCLUDE_IPMIP6MN_SERVICE_SELECTION
#undef INCLUDE_IPMIP6MN_SERVICE_VENDOR_EXTENSION
#undef INCLUDE_IPMIP6MN_MOBILE_PREFIX_RENUMBER_SUPPORT
#undef INCLUDE_IPMIP6MN_FEATURE_EXTENSION
#undef INCLUDE_IP_SECURITY
#undef INCLUDE_IPMIPPM
#undef INCLUDE_IPMIPPM_FEATURE_EXTENSION
#undef INCLUDE_IPMIPPM_PMIPV4_DHCP
#undef INCLUDE_IPMIPPM_CMD
#undef INCLUDE_IPMIP6PM
#undef INCLUDE_IPMIP6PM_LINK_FEATURE_LINK_LAYER_ADDRESS
#undef INCLUDE_IPMIP6PM_LINK_FEATURE_LINK_LOCAL_ADDRESS
#undef INCLUDE_IPMIP6PM_DUAL_STACK
#undef INCLUDE_IPMIP6PM_SERVICE_FEATURE_DHCP_RELAY
#undef INCLUDE_IPMIP6PM_SERVICE_FEATURE_RADVD
#undef INCLUDE_IPMIP6PM_SERVICE_FEATURE_SERVICE_SELECTION
#undef INCLUDE_IPMIP6PM_SERVICE_FEATURE_VENDOR_EXTENSION
#undef INCLUDE_IPMIP6PM_DUAL_STACK_DHCP_RELAY_SUPPORT
#undef INCLUDE_IPMIP6PM_DUAL_STACK_DHCP_SERVER_SUPPORT
#undef INCLUDE_IPMIP6PM_SERVICE_FEATURE_EXTENSION
#undef INCLUDE_IPMIP6PM_LINK_FEATURE_EXTENSION
#undef INCLUDE_IPMIP6PM_CMD
#undef INCLUDE_IPPPP
#undef INCLUDE_IPPPP_INTERFACE_CONFIG
#undef INCLUDE_IPPPP_USERS_CONFIG
#undef INCLUDE_IPPPPOE
#undef INCLUDE_IPPPP_CMD
#undef INCLUDE_IPPPPMP
#undef INCLUDE_IPPPP_VJCOMP
#undef INCLUDE_IPCOM_USE_INET6_ONLY
#undef INCLUDE_IPV6
#undef INCLUDE_IPNET6_AUTOCONF_PRIVACY_EXT
#undef INCLUDE_IPNET6_PRIVACY_GLOBAL_CONFIGS
#undef INCLUDE_IPNET6_PRIVACY_INTERFACE_CONFIGS
#undef INCLUDE_IPNET_USE_NAT
#undef INCLUDE_IPNET_CLASSIFIER
#undef INCLUDE_IPNET_DIFFSERV
#undef INCLUDE_IPNET_DS_SM
#undef INCLUDE_IPNET_DS_SRTCM
#undef INCLUDE_IPQOS_CMD
#undef INCLUDE_IPQUEUE_CONFIG_CMD
#undef INCLUDE_IPNET_IFQUEUE_FIFO_DEFAULT
#undef INCLUDE_IPRIP
#undef INCLUDE_IPRIP_CTRL_CMD
#undef INCLUDE_IPRIP_IFCONFIG_1
#undef INCLUDE_IPRIP_IFCONFIG_2
#undef INCLUDE_IPRIP_IFCONFIG_3
#undef INCLUDE_IPRIP_IFCONFIG_4
#undef INCLUDE_IPRIP_STATIC_ROUTE_1
#undef INCLUDE_IPRIP_STATIC_ROUTE_2
#undef INCLUDE_IPRIP_STATIC_ROUTE_3
#undef INCLUDE_RIPNG
#undef INCLUDE_RIPNG_CTRL_CMD
#undef INCLUDE_IPSCTP
#undef INCLUDE_IPARP_CMD
#undef INCLUDE_IPCOM_SYSLOGD_CMD
#undef INCLUDE_IPCOM_SYSLOGD_USE_LOG_FILE
#undef INCLUDE_IPCOM_SYSVAR_CMD
#undef INCLUDE_IPECHO_CLIENT_CMD
#undef INCLUDE_IPECHO_SERVER_CMD
#undef INCLUDE_IPFTP_CMD
#undef INCLUDE_IPD_CMD
#undef INCLUDE_IPNET_CTRL_CMD
#undef INCLUDE_IPMEM_DEBUG_CMD
#undef INCLUDE_IPNAT_CMD
#undef INCLUDE_IPNDP_CMD
#undef INCLUDE_IPNETSTAT_CMD
#undef INCLUDE_IPNSLOOKUP_CMD
#undef INCLUDE_IPPING_CMD
#undef INCLUDE_IPPING6_CMD
#undef INCLUDE_IPRADVD_CMD
#undef INCLUDE_IPROUTE_CMD
#undef INCLUDE_IPNET_PCAP_CMD
#undef INCLUDE_IPSNTP_CMD
#undef INCLUDE_IPSOCKPERF_CMD
#undef INCLUDE_IPSOCKTEST_CMD
#undef INCLUDE_IPSYSCTL_CMD
#undef INCLUDE_IPTRACE_ROUTE_CMD
#undef INCLUDE_IPTCP_TEST_CMD
#undef INCLUDE_IPTFTP_CLIENT_CMD
#undef INCLUDE_IPCOM_USE_TIME_CMD
#undef INCLUDE_IPVERSION_CMD
#undef INCLUDE_IPCOM_USE_MIB2_CMD
#undef INCLUDE_IPCOM_CPU_CMD
#undef INCLUDE_USER_CMD
#undef INCLUDE_IPNET_USE_NETLINKSOCK
#undef INCLUDE_JOB_QUEUE_UTIL
#undef INCLUDE_IPWRAP_ARP
#undef INCLUDE_NET_BOOT_IPV6_CFG
#undef INCLUDE_END2_LINKBUFPOOL
#undef INCLUDE_END_POLLED_STATS
#undef INCLUDE_FTP6
#undef INCLUDE_IPWRAP_GETADDRINFO
#undef INCLUDE_GETADDRINFO_SYSCTL
#undef INCLUDE_IPWRAP_GETNAMEINFO
#undef INCLUDE_GETNAMEINFO_SYSCTL
#undef INCLUDE_GETSERVBYPORT
#undef INCLUDE_IPWRAP_GETSERVBYNAME
#undef INCLUDE_IPWRAP_GETSERVBYPORT
#undef INCLUDE_NET_HOST_SHOW
#undef INCLUDE_HOST_TBL_SYSCTL
#undef INCLUDE_NET_INIT
#undef INCLUDE_MUX_OVER_END2
#undef INCLUDE_MUXTK_OVER_END2
#undef INCLUDE_MUX_IF_FUNC_DBASE
#undef INCLUDE_NETBUFADVLIB
#undef INCLUDE_NETPOOLSHOW
#undef INCLUDE_MBUF_UTIL2
#undef INCLUDE_NETSTAT_UN_COMP
#undef INCLUDE_IPWRAP_NETSTAT
#undef INCLUDE_PING6
#undef INCLUDE_IPWRAP_PING6
#undef INCLUDE_IPWRAP_PING
#undef INCLUDE_IPWRAP_IPPROTO
#undef INCLUDE_IP6ATTACH
#undef INCLUDE_REMLIB_SYSCTL
#undef INCLUDE_RLOGIN
#undef INCLUDE_IPWRAP_ROUTECMD
#undef INCLUDE_XDR_BOOL_T
#undef INCLUDE_IPNET_SYSCTL
#undef INCLUDE_TELNET_CLIENT
#undef INCLUDE_VXMUX_PKT_POOL_MIN
#undef INCLUDE_VXMUX_SLAB
#undef INCLUDE_VXMUX_CMD_VXSLAB
#undef INCLUDE_IPDHCPR
#undef INCLUDE_IPDHCPS
#undef INCLUDE_IPDHCPC6
#undef INCLUDE_IPDHCPS6
#undef INCLUDE_IPDHCPS6_CMD
#undef INCLUDE_L2CONFIG
#undef INCLUDE_MUX_L2
#undef INCLUDE_QOS_INGRESS
#undef INCLUDE_INTERNET_KEY_EXCHANGE
#undef INCLUDE_SSH
#undef INCLUDE_IPWRAP_IFSHOW
#undef INCLUDE_IPWRAP_GETHOSTBYNAME
#undef INCLUDE_IPWRAP_GETHOSTBYADDR
#undef INCLUDE_IPWRAP_IFNAME
#undef INCLUDE_IPWRAP_GETIFADDRS
#undef INCLUDE_IPWRAP_SNTPCTIMEGET
#undef INCLUDE_IPWRAP_SNTPSCLOCKSET
#undef INCLUDE_IPWRAP_SNTPSNSECTOFRACTION
#undef INCLUDE_IPWRAP_IFLIB
#undef INCLUDE_IPWRAP_IFLIB_TEST
#undef INCLUDE_IPWRAP_IF6LIB
#undef INCLUDE_IPWRAP_IF6LIB_TEST
#undef INCLUDE_IPWRAP_OLDROUTELIB
#undef INCLUDE_IPSEND
#undef INCLUDE_CGA_CMD
#undef INCLUDE_IPCOM_USE_KEY_DB
#undef INCLUDE_IPCRYPTO_USE_KEY_DB_EXAMPLE_KEYS
#undef INCLUDE_IPCOM_KEY_DB_CMD
#undef INCLUDE_IP8021X_SUPPLICANT
#undef INCLUDE_DOT1X_SUPP_LEGACY_API
#undef INCLUDE_IP8021X_SUPPLICANT_MIB
#undef INCLUDE_IPDIAMETER_EAP
#undef INCLUDE_IPDIAMETER_TLS_CFG
#undef INCLUDE_IPDIAMETERP
#undef INCLUDE_IPDIAMETERC_CMD
#undef INCLUDE_IPDIAMETERP_CMD
#undef INCLUDE_IPEAP
#undef INCLUDE_IPEAP_TLS_COMMON
#undef INCLUDE_IPEAP_USE_EAP_MD5
#undef INCLUDE_IPEAP_USE_EAP_GTC
#undef INCLUDE_IPEAP_USE_EAP_LEAP
#undef INCLUDE_IPEAP_USE_EAP_MSCHAPV2
#undef INCLUDE_IPEAP_USE_EAP_TLS
#undef INCLUDE_IPEAP_USE_EAP_TTLS
#undef INCLUDE_IPEAP_USE_EAP_PEAP
#undef INCLUDE_IPEAP_USE_EAP_SIM
#undef INCLUDE_IPEAP_USE_EAP_AKA
#undef INCLUDE_IPEAP_USE_EAP_WSC
#undef INCLUDE_IPMCP
#undef INCLUDE_IPMCP_USE_IGMP
#undef INCLUDE_IPMCP_USE_MLD
#undef INCLUDE_IPMCAST_PROXY_CMD
#undef INCLUDE_IPMPLS
#undef INCLUDE_IPRADIUS_CMD
#undef INCLUDE_IPROHC
#undef INCLUDE_IPROHC_CMD
#undef INCLUDE_IPROHC_PROFILE_UNCOMPRESSED
#undef INCLUDE_IPROHC_PROFILE_IP
#undef INCLUDE_IPCAVIUM
#undef INCLUDE_IPHWCRYPTO
#undef INCLUDE_IPCAVIUM_CMD
#undef INCLUDE_IPFREESCALE
#undef INCLUDE_IPFREESCALE_CMD
#undef INCLUDE_IPSECCTRL_CMD
#undef INCLUDE_KEYADM_CMD
#undef INCLUDE_IPCRYPTO_USE_CMDS
#undef INCLUDE_IPCRYPTO_USE_TEST_CMDS
#undef INCLUDE_IPSSL
#undef INCLUDE_IFPROXY
#undef INCLUDE_IPNET_USE_MCAST_ROUTING
#undef INCLUDE_IPNET_USE_TUNNEL
#undef INCLUDE_IPNET6_USE_MCAST_ROUTING
#undef INCLUDE_IPMPLS_TUNNEL
#undef INCLUDE_IPCOM_USE_AUTH_RADIUS
#undef INCLUDE_IPSSL_USE_CMDS
#undef INCLUDE_IPSSL_USE_TEST_CMDS
#undef INCLUDE_IPNET_USE_VLAN
#undef INCLUDE_IPVRRPD
#undef INCLUDE_WRNAD
#undef INCLUDE_MIB_CONFIG
#undef INCLUDE_AUTHENTICATOR_CONFIG
#undef INCLUDE_AUTHENTICATOR_PRIMARY_RADIUS_SERVER
#undef INCLUDE_AUTHENTICATOR_SECONDARY_RADIUS_SERVER
#undef INCLUDE_WINDML_ALL
#undef INCLUDE_WINDML_NECESSARY
#undef INCLUDE_WINDML
#undef INCLUDE_PCI_WINDML_GRAPHICS
#undef INCLUDE_WINDML_GRAPHICS_SHARED_DATA
#undef INCLUDE_WINDML_GRAPHICS_NO_SHARED_DATA
#undef INCLUDE_INTEL_CPU_SHOW
#undef INCLUDE_PCPENTIUM4_PARAMS
#undef INCLUDE_DEBUG_STORE
#undef INCLUDE_MMU_P6_36BIT
#undef INCLUDE_FEI_END


/*** PARAMETERS ***/

#undef  DEFAULT_BOOT_LINE
#define DEFAULT_BOOT_LINE "gei(0,0)host:vxWorks h=192.168.10.102 e=192.168.10.145:ffffff00 f=0x08 u=target pw=password tn=CD6020SMP o=gei"
#undef  LOCAL_MEM_LOCAL_ADRS
#define LOCAL_MEM_LOCAL_ADRS (0x00100000)
#undef  LOCAL_MEM_SIZE
#define LOCAL_MEM_SIZE (SYSTEM_RAM_SIZE - LOCAL_MEM_LOCAL_ADRS)
#undef  LOCAL_MEM_AUTOSIZE
#undef  USER_RESERVED_MEM
#define USER_RESERVED_MEM (0)
#undef  NV_RAM_SIZE
#define NV_RAM_SIZE (NONE)
#undef  NV_BOOT_OFFSET
#define NV_BOOT_OFFSET 0
#undef  VEC_BASE_ADRS
#define VEC_BASE_ADRS ((char *) LOCAL_MEM_LOCAL_ADRS)
#undef  EXC_MSG_OFFSET
#define EXC_MSG_OFFSET 0x1300
#undef  EXC_MSG_ADRS
#define EXC_MSG_ADRS ((char *) (LOCAL_MEM_LOCAL_ADRS+EXC_MSG_OFFSET))
#undef  BOOT_LINE_SIZE
#define BOOT_LINE_SIZE 255
#undef  BOOT_LINE_ADRS
#define BOOT_LINE_ADRS ((char *) (LOCAL_MEM_LOCAL_ADRS+BOOT_LINE_OFFSET))
#undef  BOOT_LINE_OFFSET
#define BOOT_LINE_OFFSET 0x1200
#undef  RESERVED
#define RESERVED 0
#undef  FREE_RAM_ADRS
#define FREE_RAM_ADRS (end)
#undef  ROM_WARM_ADRS
#define ROM_WARM_ADRS ("unused")
#undef  STACK_SAVE
#define STACK_SAVE 0x40
#undef  RAM_HIGH_ADRS
#define RAM_HIGH_ADRS 0x00108000
#undef  RAM_LOW_ADRS
#define RAM_LOW_ADRS 0x00408000
#undef  ROM_BASE_ADRS
#define ROM_BASE_ADRS (0x00008000)
#undef  ROM_TEXT_ADRS
#define ROM_TEXT_ADRS (ROM_BASE_ADRS)
#undef  ROM_SIZE
#define ROM_SIZE (0x00090000)
#undef  USER_I_CACHE_MODE
#define USER_I_CACHE_MODE CACHE_WRITETHROUGH
#undef  USER_D_CACHE_MODE
#define USER_D_CACHE_MODE (CACHE_COPYBACK | CACHE_SNOOP_ENABLE)
#undef  USER_I_CACHE_ENABLE
#define USER_I_CACHE_ENABLE
#undef  USER_D_CACHE_ENABLE
#define USER_D_CACHE_ENABLE
#undef  SW_MMU_ENABLE
#define SW_MMU_ENABLE FALSE
#undef  VM_PAGE_SIZE
#define VM_PAGE_SIZE PAGE_SIZE_4KB
#undef  USER_D_MMU_ENABLE
#define USER_D_MMU_ENABLE
#undef  USER_I_MMU_ENABLE
#define USER_I_MMU_ENABLE
#undef  SYS_CLK_RATE
#define SYS_CLK_RATE 60
#undef  SYS_CLK_RATE_MIN
#define SYS_CLK_RATE_MIN (19)
#undef  SYS_CLK_RATE_MAX
#define SYS_CLK_RATE_MAX (5000)
#undef  NUM_TTY
#define NUM_TTY (N_UART_CHANNELS)
#undef  CONSOLE_TTY
#define CONSOLE_TTY 0
#undef  CONSOLE_BAUD_RATE
#define CONSOLE_BAUD_RATE 9600
#undef  N_VIRTUAL_CONSOLES
#define N_VIRTUAL_CONSOLES (2)
#undef  PC_CONSOLE
#define PC_CONSOLE (0)
#undef  XBD_BLK_DEV_TASK_PRIORITY
#define XBD_BLK_DEV_TASK_PRIORITY 200
#undef  XBD_BLK_DEV_DIRECT_BIO_HANDLING
#define XBD_BLK_DEV_DIRECT_BIO_HANDLING FALSE
#undef  CLEAR_BSS
#define CLEAR_BSS
#undef  TIP_CONFIG_STRING
#define TIP_CONFIG_STRING ""
#undef  TIP_ESCAPE_CHARACTER
#define TIP_ESCAPE_CHARACTER "~"
#undef  ROOT_STACK_SIZE
#define ROOT_STACK_SIZE 10000
#undef  ISR_STACK_SIZE
#define ISR_STACK_SIZE 1000
#undef  INT_LOCK_LEVEL
#define INT_LOCK_LEVEL 0x0
#undef  TASK_USER_EXC_STACK_SIZE
#define TASK_USER_EXC_STACK_SIZE 8192
#undef  TASK_USER_EXC_STACK_OVERFLOW_SIZE
#define TASK_USER_EXC_STACK_OVERFLOW_SIZE 4096
#undef  TASK_USER_EXEC_STACK_OVERFLOW_SIZE
#define TASK_USER_EXEC_STACK_OVERFLOW_SIZE 4096
#undef  TASK_USER_EXEC_STACK_UNDERFLOW_SIZE
#define TASK_USER_EXEC_STACK_UNDERFLOW_SIZE 4096
#undef  TASK_KERNEL_EXEC_STACK_OVERFLOW_SIZE
#define TASK_KERNEL_EXEC_STACK_OVERFLOW_SIZE 4096
#undef  TASK_KERNEL_EXEC_STACK_UNDERFLOW_SIZE
#define TASK_KERNEL_EXEC_STACK_UNDERFLOW_SIZE 4096
#undef  TASK_PRIORITY_SET_COMPATIBLE
#define TASK_PRIORITY_SET_COMPATIBLE FALSE
#undef  WIND_JOBS_MAX
#define WIND_JOBS_MAX 64
#undef  VX_GLOBAL_NO_STACK_FILL
#define VX_GLOBAL_NO_STACK_FILL FALSE
#undef  MAX_REBOOT_HOOKS
#define MAX_REBOOT_HOOKS 8
#undef  ENV_VAR_USE_HOOKS
#define ENV_VAR_USE_HOOKS TRUE
#undef  MAX_ISR_JOBS
#define MAX_ISR_JOBS 16
#undef  JOB_TASK_STACK_SIZE
#define JOB_TASK_STACK_SIZE 8000
#undef  ISR_DEFER_MODE
#define ISR_DEFER_MODE ISR_DEFER_MODE_PER_CPU
#undef  FUNCPTR_OBJ_MEMALLOC_RTN
#define FUNCPTR_OBJ_MEMALLOC_RTN memPartAlloc
#undef  FUNCPTR_OBJ_MEMFREE_RTN
#define FUNCPTR_OBJ_MEMFREE_RTN memPartFree
#undef  OBJ_MEM_POOL_ID
#define OBJ_MEM_POOL_ID memSysPartId
#undef  OBJ_LIBRARY_OPTIONS
#define OBJ_LIBRARY_OPTIONS 0
#undef  VXEVENTS_OPTIONS
#define VXEVENTS_OPTIONS EVENTS_NONINTERRUPTIBLE
#undef  SEM_RW_MAX_CONCURRENT_READERS
#define SEM_RW_MAX_CONCURRENT_READERS 32
#undef  MEM_PART_DEFAULT_OPTIONS
#define MEM_PART_DEFAULT_OPTIONS (MEM_ALLOC_ERROR_LOG_FLAG | MEM_ALLOC_ERROR_EDR_WARN_FLAG | MEM_BLOCK_ERROR_LOG_FLAG | MEM_BLOCK_ERROR_EDR_WARN_FLAG | MEM_BLOCK_ERROR_SUSPEND_FLAG | MEM_BLOCK_CHECK)
#undef  POSIX_SIGNAL_MODE
#define POSIX_SIGNAL_MODE FALSE
#undef  VX_TRAD_SCHED_CONSTANT_RDY_Q
#define VX_TRAD_SCHED_CONSTANT_RDY_Q TRUE
#undef  IOS_POSIX_PSE52_MODE
#define IOS_POSIX_PSE52_MODE FALSE
#undef  NUM_DRIVERS
#define NUM_DRIVERS 20
#undef  NUM_FILES
#define NUM_FILES 50
#undef  MAX_LOG_MSGS
#define MAX_LOG_MSGS 50
#undef  INIT_NBIO_MSGS
#define INIT_NBIO_MSGS 32
#undef  TYLIB_XOFF_PCNT
#define TYLIB_XOFF_PCNT 85
#undef  TYLIB_XON_PCNT
#define TYLIB_XON_PCNT 50
#undef  TYLIB_WRT_THRESHLD
#define TYLIB_WRT_THRESHLD 20
#undef  NUM_RAWFS_FILES
#define NUM_RAWFS_FILES 5
#undef  ERF_MAX_USR_CATEGORIES
#define ERF_MAX_USR_CATEGORIES 16
#undef  ERF_MAX_USR_TYPES
#define ERF_MAX_USR_TYPES 16
#undef  DEVICE_MANAGER_MAX_NUM_DEVICES
#define DEVICE_MANAGER_MAX_NUM_DEVICES 255
#undef  LOGIN_USER_NAME
#define LOGIN_USER_NAME "target"
#undef  LOGIN_PASSWORD
#define LOGIN_PASSWORD "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg="
#undef  WDB_COMM_PORT
#define WDB_COMM_PORT 0x4321
#undef  WDB_STACK_SIZE
#define WDB_STACK_SIZE 0x2000
#undef  WDB_POOL_SIZE
#define WDB_POOL_SIZE ((unsigned int) (sysMemTop() - FREE_RAM_ADRS)/16)
#undef  WDB_BP_MAX
#define WDB_BP_MAX 25
#undef  WDB_GOPHER_TAPE_LEN
#define WDB_GOPHER_TAPE_LEN 1400
#undef  WDB_GOPHER_TAPE_NB
#define WDB_GOPHER_TAPE_NB 10
#undef  WDB_REGS_SIZE
#define WDB_REGS_SIZE 512
#undef  WDB_MTU
#define WDB_MTU 1500
#undef  WDB_END_DEVICE_NAME
#define WDB_END_DEVICE_NAME NULL
#undef  WDB_END_DEVICE_UNIT
#define WDB_END_DEVICE_UNIT 0
#undef  WDB_END_DEVICE_ADDRESS
#define WDB_END_DEVICE_ADDRESS NULL
#undef  WDB_SPAWN_PRI
#define WDB_SPAWN_PRI 100
#undef  WDB_SPAWN_OPTS
#define WDB_SPAWN_OPTS VX_FP_TASK
#undef  WDB_SPAWN_STACK_SIZE
#define WDB_SPAWN_STACK_SIZE 0x5000
#undef  WDB_TASK_PRIORITY
#define WDB_TASK_PRIORITY 3
#undef  WDB_TASK_OPTIONS
#define WDB_TASK_OPTIONS VX_UNBREAKABLE | VX_FP_TASK
#undef  WDB_RESTART_TIME
#define WDB_RESTART_TIME 10
#undef  WDB_MAX_RESTARTS
#define WDB_MAX_RESTARTS 5
#undef  STORE_ABS_SYMBOLS
#define STORE_ABS_SYMBOLS FALSE
#undef  SYM_TBL_HASH_SIZE_LOG2
#define SYM_TBL_HASH_SIZE_LOG2 8
#undef  SHELL_TASK_NAME_BASE
#define SHELL_TASK_NAME_BASE "tShell"
#undef  SHELL_TASK_PRIORITY
#define SHELL_TASK_PRIORITY 1
#undef  SHELL_TASK_OPTIONS
#define SHELL_TASK_OPTIONS (VX_FP_TASK | VX_UNBREAKABLE | COPROCS_ALL | VX_PRIVATE_ENV)
#undef  SHELL_STACK_SIZE
#define SHELL_STACK_SIZE 0x10000
#undef  SHELL_SECURE
#define SHELL_SECURE FALSE
#undef  SHELL_START_AT_BOOT
#define SHELL_START_AT_BOOT TRUE
#undef  SHELL_COMPATIBLE
#define SHELL_COMPATIBLE FALSE
#undef  SHELL_DEFAULT_CONFIG
#define SHELL_DEFAULT_CONFIG "LINE_EDIT_MODE=,LINE_LENGTH=256,STRING_FREE=manual,INTERPRETER=,VXE_PATH=.;/romfs"
#undef  SHELL_FIRST_CONFIG
#define SHELL_FIRST_CONFIG NULL
#undef  SHELL_REMOTE_CONFIG
#define SHELL_REMOTE_CONFIG NULL
#undef  SHELL_MAX_SESSIONS
#define SHELL_MAX_SESSIONS -1
#undef  DOSFS_DEFAULT_MAX_FILES
#define DOSFS_DEFAULT_MAX_FILES 20
#undef  DOSFS_DEFAULT_CREATE_OPTIONS
#define DOSFS_DEFAULT_CREATE_OPTIONS 0x04
#undef  DOSFS_DEFAULT_VOL_BIO_BUFFER_SIZE
#define DOSFS_DEFAULT_VOL_BIO_BUFFER_SIZE 32
#undef  HWMEM_POOL_SIZE
#define HWMEM_POOL_SIZE 100000
#undef  SYSCLK_TIMER_NAME
#define SYSCLK_TIMER_NAME NULL
#undef  SYSCLK_TIMER_UNIT
#define SYSCLK_TIMER_UNIT 0
#undef  SYSCLK_TIMER_NUM
#define SYSCLK_TIMER_NUM 0
#undef  AUXCLK_TIMER_NAME
#define AUXCLK_TIMER_NAME NULL
#undef  AUXCLK_TIMER_UNIT
#define AUXCLK_TIMER_UNIT 0
#undef  AUXCLK_TIMER_NUM
#define AUXCLK_TIMER_NUM 0
#undef  TIMESTAMP_TIMER_NAME
#define TIMESTAMP_TIMER_NAME NULL
#undef  TIMESTAMP_TIMER_UNIT
#define TIMESTAMP_TIMER_UNIT 0
#undef  TIMESTAMP_TIMER_NUM
#define TIMESTAMP_TIMER_NUM 0
#undef  USB_GEN2_HELPER_LATENCY
#define USB_GEN2_HELPER_LATENCY 1000
#undef  USB_GEN2_HELPER_PRIORITY
#define USB_GEN2_HELPER_PRIORITY 150
#undef  USB_GEN2_HELPER_DELETABLE_QUEUE_SIZE
#define USB_GEN2_HELPER_DELETABLE_QUEUE_SIZE 100
#undef  USB_HUB_POLLING_INTERVAL
#define USB_HUB_POLLING_INTERVAL 2
#undef  USB_MEM_PART_SIZE
#define USB_MEM_PART_SIZE 0x200000
#undef  USB_CHECK_RESUBMIT_URB_FLAG
#define USB_CHECK_RESUBMIT_URB_FLAG FALSE
#undef  USB2_MSC_DRIVE_NAME
#define USB2_MSC_DRIVE_NAME "/bd"
#undef  USB2_MSC_MAX_NAME_SZ
#define USB2_MSC_MAX_NAME_SZ 50
#undef  USB2_MSC_SERVICE_TASK_NAME
#define USB2_MSC_SERVICE_TASK_NAME "tUsb2Msc"
#undef  USB2_MSC_MAX_DEVICES
#define USB2_MSC_MAX_DEVICES 10
#undef  USB2_MSC_MAX_DRIVES
#define USB2_MSC_MAX_DRIVES 16
#undef  USB2_MSC_DIRECT_ACCESS_BASE_NAME
#define USB2_MSC_DIRECT_ACCESS_BASE_NAME "/usb2Msc"
#undef  USB2_MSC_COMPLIANCE_LOG_FILE_BASE_NAME
#define USB2_MSC_COMPLIANCE_LOG_FILE_BASE_NAME "stdout"
#undef  USB2_MSC_FS_INTERFACE_NAME
#define USB2_MSC_FS_INTERFACE_NAME "XBD"
#undef  USB2_MSC_DIRECT_ACCESS_ENABLE
#define USB2_MSC_DIRECT_ACCESS_ENABLE FALSE
#undef  USB2_MSC_COMPLIANCE_ENABLE
#define USB2_MSC_COMPLIANCE_ENABLE FALSE
#undef  USB2_MSC_MEDIUM_HOTPLUG_CHECK_ENABLE
#define USB2_MSC_MEDIUM_HOTPLUG_CHECK_ENABLE TRUE
#undef  USB2_MSC_WRITE_PROTECTION_CHECK_ENABLE
#define USB2_MSC_WRITE_PROTECTION_CHECK_ENABLE FALSE
#undef  USB2_MSC_MEDIUM_HOTPLUG_CHECK_INTERVAL
#define USB2_MSC_MEDIUM_HOTPLUG_CHECK_INTERVAL 2000
#undef  USB2_MSC_STATUS_CHECK_ENABLE
#define USB2_MSC_STATUS_CHECK_ENABLE TRUE
#undef  USB2_MSC_RESET_TIMEOUT
#define USB2_MSC_RESET_TIMEOUT 2000
#undef  USB2_MSC_COMMAND_TIMEOUT
#define USB2_MSC_COMMAND_TIMEOUT 2000
#undef  USB2_MSC_STATUS_TIMEOUT
#define USB2_MSC_STATUS_TIMEOUT 2000
#undef  USB2_MSC_MAX_TRANSFER_BLOCKS
#define USB2_MSC_MAX_TRANSFER_BLOCKS 64
#undef  USB2_MSC_SERVICE_TASK_PRIORITY
#define USB2_MSC_SERVICE_TASK_PRIORITY 150
#undef  USB2_MSC_SERVICE_TASK_OPTIONS
#define USB2_MSC_SERVICE_TASK_OPTIONS 0
#undef  USB2_MSC_SERVICE_TASK_STACK_SIZE
#define USB2_MSC_SERVICE_TASK_STACK_SIZE 4096
#undef  USB2_MSC_XBD_DIRECT_BIO
#define USB2_MSC_XBD_DIRECT_BIO FALSE
#undef  ICH_DIRECT_BIO_HANDLING
#define ICH_DIRECT_BIO_HANDLING FALSE
#undef  CPU_PWR_TASK_P_STATE
#define CPU_PWR_TASK_P_STATE (cpuPwrP0State)
#undef  CPU_PWR_ISR_P_STATE
#define CPU_PWR_ISR_P_STATE (0)
#undef  CPU_PWR_UTIL_PERIOD1
#define CPU_PWR_UTIL_PERIOD1 (300)
#undef  CPU_PWR_UTIL_PERIOD2
#define CPU_PWR_UTIL_PERIOD2 (1000)
#undef  CPU_PWR_HIGH_THRESHOLD
#define CPU_PWR_HIGH_THRESHOLD (100)
#undef  CPU_PWR_LOW_THRESHOLD
#define CPU_PWR_LOW_THRESHOLD (0)
#undef  IPCOM_AUTH_HASH_HOOK
#define IPCOM_AUTH_HASH_HOOK NULL
#undef  IPCOM_AUTH_HASH_HOOK_INSTALL
#define IPCOM_AUTH_HASH_HOOK_INSTALL FALSE
#undef  IPCOM_AUTH_HASH_HOOK_DIGEST
#define IPCOM_AUTH_HASH_HOOK_DIGEST 0
#undef  IFCONFIG_1
#define IFCONFIG_1 "ifname","devname driver","inet driver", "gateway driver"
#undef  IFCONFIG_LOOPBACK
#define IFCONFIG_LOOPBACK "ifname lo0","inet 127.0.0.1/32","inet6 ::1/128","inet6 FF01::1/16"
#undef  INET_IPAIP_IFNAME_LIST
#define INET_IPAIP_IFNAME_LIST ""
#undef  INET_IPAIP_PROBE_WAIT
#define INET_IPAIP_PROBE_WAIT "1"
#undef  INET_IPAIP_PROBE_NUM
#define INET_IPAIP_PROBE_NUM "3"
#undef  INET_IPAIP_PROBE_MIN
#define INET_IPAIP_PROBE_MIN "1"
#undef  INET_IPAIP_PROBE_MAX
#define INET_IPAIP_PROBE_MAX "3"
#undef  INET_IPAIP_ANNOUNCE_WAIT
#define INET_IPAIP_ANNOUNCE_WAIT "2"
#undef  INET_IPAIP_ANNOUNCE_NUM
#define INET_IPAIP_ANNOUNCE_NUM "2"
#undef  INET_IPAIP_ANNOUNCE_INTERVAL
#define INET_IPAIP_ANNOUNCE_INTERVAL "2"
#undef  INET_IPAIP_MAX_CONFLICTS
#define INET_IPAIP_MAX_CONFLICTS "10"
#undef  INET_IPAIP_RATE_LIMIT_INTERVAL
#define INET_IPAIP_RATE_LIMIT_INTERVAL "60"
#undef  INET_IPAIP_DEFEND_INTERVAL
#define INET_IPAIP_DEFEND_INTERVAL "10"
#undef  FTPS_AUTH_ATTEMPTS
#define FTPS_AUTH_ATTEMPTS "3"
#undef  FTPS_SLEEP_TIME
#define FTPS_SLEEP_TIME "5"
#undef  FTPS_LOCAL_PORT_BASE
#define FTPS_LOCAL_PORT_BASE "49151"
#undef  FTPS_PEER_PORT_BASE
#define FTPS_PEER_PORT_BASE "1023"
#undef  FTPS_ENABLE_PROXY
#define FTPS_ENABLE_PROXY "0"
#undef  FTPS_MODE
#define FTPS_MODE "0"
#undef  FTPS_ROOT_DIR
#define FTPS_ROOT_DIR ""
#undef  FTPS_INITIAL_DIR
#define FTPS_INITIAL_DIR "/ata0a"
#undef  FTPS_MAX_SESSIONS
#define FTPS_MAX_SESSIONS "8"
#undef  FTPS_PORT_NUM
#define FTPS_PORT_NUM "21"
#undef  FTPS_RECV_TIMEOUT
#define FTPS_RECV_TIMEOUT "30"
#undef  FTPS_SEND_TIMEOUT
#define FTPS_SEND_TIMEOUT "30"
#undef  FTPS_INACTIVITY_TIMEOUT
#define FTPS_INACTIVITY_TIMEOUT "300"
#undef  FTPS_SOCKET_BACKLOG
#define FTPS_SOCKET_BACKLOG "0"
#undef  FTPS_SYS_TYPE
#define FTPS_SYS_TYPE "UNIX"
#undef  FTPS_INSTALL_CALLBACK_HOOK
#define FTPS_INSTALL_CALLBACK_HOOK FALSE
#undef  FTPS_AUTH_CALLBACK_HOOK
#define FTPS_AUTH_CALLBACK_HOOK NULL
#undef  INET_ENABLE_PROXY_ARP
#define INET_ENABLE_PROXY_ARP "0"
#undef  INET_AUTO_PROXY_ARP
#define INET_AUTO_PROXY_ARP "0"
#undef  INET_IFLIST_ENABLE_PROXY_ARP
#define INET_IFLIST_ENABLE_PROXY_ARP ""
#undef  INET_IFLIST_AUTO_PROXY_ARP
#define INET_IFLIST_AUTO_PROXY_ARP ""
#undef  IPNET_MAX_INPUT_PKTS
#define IPNET_MAX_INPUT_PKTS 32
#undef  IPNET_REASSEMBLY_TIMEOUT
#define IPNET_REASSEMBLY_TIMEOUT 60
#undef  IPNET_CACHE_BUFSIZE
#define IPNET_CACHE_BUFSIZE 0
#undef  IPNET_MEMORY_LIMIT
#define IPNET_MEMORY_LIMIT 16777216
#undef  IPNET_MAX_REASSEMBLY_LIST_LEN
#define IPNET_MAX_REASSEMBLY_LIST_LEN 10
#undef  IPNET_MAX_DGRAM_FRAG_LIST_LEN
#define IPNET_MAX_DGRAM_FRAG_LIST_LEN 100
#undef  INET_MIN_MTU_SIZE
#define INET_MIN_MTU_SIZE 576
#undef  INET_BASE_HOP_LIMIT
#define INET_BASE_HOP_LIMIT "64"
#undef  INET_SEND_GRATUITOUS_ARP
#define INET_SEND_GRATUITOUS_ARP "yes"
#undef  INET_DELETE_ADDR_ON_DUPLICATE_DETECT
#define INET_DELETE_ADDR_ON_DUPLICATE_DETECT "yes"
#undef  INET_MAX_PKTS_PENDING
#define INET_MAX_PKTS_PENDING "3"
#undef  INET_MAX_UNICAST_SOLICIT
#define INET_MAX_UNICAST_SOLICIT "1"
#undef  INET_MAX_MULTICAST_SOLICIT
#define INET_MAX_MULTICAST_SOLICIT "9"
#undef  INET_MAX_APP_SOLICIT
#define INET_MAX_APP_SOLICIT "1"
#undef  INET_BASE_REACHABLE_TIME
#define INET_BASE_REACHABLE_TIME "30"
#undef  INET_BASE_RETRANSMIT_TIME
#define INET_BASE_RETRANSMIT_TIME "1"
#undef  INET_DELAY_FIRST_PROBE_TIME
#define INET_DELAY_FIRST_PROBE_TIME "5"
#undef  INET_NBR_CACHE_TO_LIVE_TIME
#define INET_NBR_CACHE_TO_LIVE_TIME "1200"
#undef  INET_DST_CACHE_TO_LIVE_TIME
#define INET_DST_CACHE_TO_LIVE_TIME "600"
#undef  INET_DISABLE_BROADCAST_FWD
#define INET_DISABLE_BROADCAST_FWD "1"
#undef  INET_ICMP_RATE_LIMIT_BUCKET_SIZE
#define INET_ICMP_RATE_LIMIT_BUCKET_SIZE "100"
#undef  INET_ICMP_RATE_LIMIT_INTERVAL
#define INET_ICMP_RATE_LIMIT_INTERVAL "1000"
#undef  INET_ICMP_REDIRECT_SEND
#define INET_ICMP_REDIRECT_SEND "2"
#undef  INET_ICMP_REDIRECT_RECEIVE
#define INET_ICMP_REDIRECT_RECEIVE "1"
#undef  INET_ICMP_IGNORE_ECHO_REQ
#define INET_ICMP_IGNORE_ECHO_REQ "0"
#undef  INET_ICMP_IGNORE_TIMESTAMP_REQ
#define INET_ICMP_IGNORE_TIMESTAMP_REQ "0"
#undef  INET_ICMP_SEND_TIME_EXCEEDED
#define INET_ICMP_SEND_TIME_EXCEEDED "1"
#undef  INET_ICMP_SEND_DST_UNREACHABLE
#define INET_ICMP_SEND_DST_UNREACHABLE "1"
#undef  INET_ICMP_IGNORE_BROADCAST
#define INET_ICMP_IGNORE_BROADCAST "1"
#undef  TCP_CONN_TIMEOUT
#define TCP_CONN_TIMEOUT "75"
#undef  TCP_MAX_RETRANSMITS
#define TCP_MAX_RETRANSMITS "10"
#undef  TCP_MSL
#define TCP_MSL "30"
#undef  TCP_MAX_MSS
#define TCP_MAX_MSS "0"
#undef  TCP_USE_TIMESTAMP
#define TCP_USE_TIMESTAMP "0"
#undef  TCP_USE_RFC1122_URGENT_DATA
#define TCP_USE_RFC1122_URGENT_DATA "0"
#undef  TCP_SEGMENT_MULTIPLIER
#define TCP_SEGMENT_MULTIPLIER "2"
#undef  TCP_DISABLE_LAND_ATTACK
#define TCP_DISABLE_LAND_ATTACK "1"
#undef  TCP_ALLOW_ZERO_WINDOW
#define TCP_ALLOW_ZERO_WINDOW "0"
#undef  TCP_ALLOW_TINY_WINDOW
#define TCP_ALLOW_TINY_WINDOW "1"
#undef  TCP_PERSIST_TMO
#define TCP_PERSIST_TMO "0"
#undef  IPNET_SOCK_MAX
#define IPNET_SOCK_MAX 1024
#undef  IPNET_SOCK_ANON_PORT_MIN
#define IPNET_SOCK_ANON_PORT_MIN "49152"
#undef  IPNET_SOCK_ANON_PORT_MAX
#define IPNET_SOCK_ANON_PORT_MAX "65535"
#undef  IPNET_SOCK_DEFAULT_SEND_BUFSIZE
#define IPNET_SOCK_DEFAULT_SEND_BUFSIZE "10000"
#undef  IPNET_SOCK_DEFAULT_RECV_BUFSIZE
#define IPNET_SOCK_DEFAULT_RECV_BUFSIZE "10000"
#undef  IPNET_SOCK_ADDR_NOTIFY
#define IPNET_SOCK_ADDR_NOTIFY "1"
#undef  IPNET_ROUTE_MAX_CLONE_COUNT
#define IPNET_ROUTE_MAX_CLONE_COUNT "1000"
#undef  APPL_LOG_FD_CFG
#define APPL_LOG_FD_CFG STD_OUT
#undef  APPL_LOG_LEVEL_CFG
#define APPL_LOG_LEVEL_CFG (_LOG_DEC_DFLT | _LOG_LVL_DFLT)
#undef  APPL_KERN_LOG_FD_CFG
#define APPL_KERN_LOG_FD_CFG KERN_LOG_FD
#undef  APPL_KERN_LOG_LEVEL_CFG
#define APPL_KERN_LOG_LEVEL_CFG (_LOG_DEC_DFLT | _LOG_LVL_DFLT)
#undef  NET_JOB_NUM_CFG
#define NET_JOB_NUM_CFG 85
#undef  NET_TASK_PRIORITY
#define NET_TASK_PRIORITY 50
#undef  NET_TASK_OPTIONS
#define NET_TASK_OPTIONS VX_SUPERVISOR_MODE | VX_UNBREAKABLE
#undef  NET_TASK_STACKSIZE
#define NET_TASK_STACKSIZE 10000
#undef  NUM_NET_DAEMONS
#define NUM_NET_DAEMONS 1
#undef  NET_DAEMONS_CPU_AFFINITY
#define NET_DAEMONS_CPU_AFFINITY TRUE
#undef  FTP_TRANSIENT_MAX_RETRY_COUNT
#define FTP_TRANSIENT_MAX_RETRY_COUNT 100
#undef  FTP_TRANSIENT_RETRY_INTERVAL
#define FTP_TRANSIENT_RETRY_INTERVAL 0
#undef  FTP_TRANSIENT_FATAL
#define FTP_TRANSIENT_FATAL ftpTransientFatal
#undef  FTP_DEBUG_OPTIONS
#define FTP_DEBUG_OPTIONS 0
#undef  FTP_TIMEOUT
#define FTP_TIMEOUT 0
#undef  IFCONFIG_ENTRY_1
#define IFCONFIG_ENTRY_1 NULL
#undef  IFCONFIG_ENTRY_2
#define IFCONFIG_ENTRY_2 NULL
#undef  IFCONFIG_ENTRY_3
#define IFCONFIG_ENTRY_3 NULL
#undef  IFCONFIG_ENTRY_4
#define IFCONFIG_ENTRY_4 NULL
#undef  IFCONFIG_ENTRY_5
#define IFCONFIG_ENTRY_5 NULL
#undef  IFCONFIG_ENTRY_6
#define IFCONFIG_ENTRY_6 NULL
#undef  IFCONFIG_ENTRY_7
#define IFCONFIG_ENTRY_7 NULL
#undef  IFCONFIG_ENTRY_8
#define IFCONFIG_ENTRY_8 NULL
#undef  IFCONFIG_ENTRY_9
#define IFCONFIG_ENTRY_9 NULL
#undef  IFCONFIG_ENTRY_10
#define IFCONFIG_ENTRY_10 NULL
#undef  NETBUF_LEADING_CLSPACE_DRV
#define NETBUF_LEADING_CLSPACE_DRV 64
#undef  RSH_STDERR_SETUP_TIMEOUT
#define RSH_STDERR_SETUP_TIMEOUT -1
#undef  REM_NUM_CONN_RETRIALS
#define REM_NUM_CONN_RETRIALS 3
#undef  TM_MODE
#define TM_MODE GV3_AUTO
#undef  TM_AC_CHK_RTN
#define TM_AC_CHK_RTN NULL

#endif /* INCprjParamsh */
